cas/src/main/java/org/entcore/cas/services/EduMediaRegisteredService.java

EduMedia cas service v1

---

infra/src/main/resources/public/js/angular-app.js

Bugfix for redmine ticket 6113

[Calendar directive] Set year in date returned by getTimeFromBoundaries function

---

common/src/main/java/org/entcore/common/utils/DateUtils.java
common/src/main/java/org/entcore/common/utils/StringUtils.java

Add utility classes

---

infra/src/main/resources/public/js/angular-app.js
infra/src/main/resources/public/template/calendar.html

@camille-wintz Can you please review my pull request ?

calendar directive  - add readonly attribute

---

directory/src/main/java/org/entcore/directory/controllers/TimetableController.java
directory/src/main/java/org/entcore/directory/services/TimetableService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultTimetableService.java

* Get courses between two dates can filter on group name
* Get subjects return subjects that don't have 'teaches' relationship

[Evo][Timetable] : Update api

---

admin/src/main/resources/public/styles/admin.scss

issue 20310: http://support.web-education.net/issues/20310
This PR is a cherry-pick of the commit 047038e626c1ee2ca1fcc62940a68fae749542f9 and a commit to fix the waiting predelete icon in the user list.

Fix unicode content of waiting predelete icon

---

admin/src/main/ts/app/structure/cards/quick-actions-card.component.ts

Related to issue CAV2-367: https://opendigitaleducation.atlassian.net/browse/CAV2-367

Activate 'create group' quick action

---

admin/src/main/ts/app/core/store/global.store.ts
admin/src/main/ts/app/core/store/models/user.model.ts
admin/src/main/ts/app/users/details/sections/classes/user-classes-section.component.ts
admin/src/main/ts/app/users/details/sections/functionalgroups/user-functionalgroups-section.component.ts
admin/src/main/ts/app/users/details/sections/isGroupManageable.spec.ts
admin/src/main/ts/app/users/details/sections/isGroupManageable.ts
admin/src/main/ts/app/users/details/sections/manualgroups/user-manualgroups-section.component.spec.ts
admin/src/main/ts/app/users/details/sections/manualgroups/user-manualgroups-section.component.ts
admin/src/main/ts/app/users/users.module.ts

Related to issue CAV2-371: https://opendigitaleducation.atlassian.net/browse/CAV2-371

Groups not in the structure should not visible be in the user details

---

admin/src/main/ts/app/core/nav/nav.component.ts
admin/src/main/ts/app/groups/details/manage-users/input/group-input-users.component.ts
admin/src/main/ts/app/groups/details/manage-users/output/group-output-users.component.ts
admin/src/main/ts/app/groups/details/users-list/group-users-list.component.ts
admin/src/main/ts/app/shared/ux/components/datepicker.component.ts
admin/src/main/ts/app/users/create/user-create.component.ts
admin/src/main/ts/app/users/details/sections/children/user-children-section.component.ts
admin/src/main/ts/app/users/details/sections/classes/user-classes-section.component.ts
admin/src/main/ts/app/users/details/sections/duplicates/user-duplicates.section.component.ts
admin/src/main/ts/app/users/details/sections/functionalgroups/user-functionalgroups-section.component.ts
admin/src/main/ts/app/users/details/sections/manualgroups/user-manualgroups-section.component.ts
admin/src/main/ts/app/users/details/sections/relatives/user-relatives-section.component.ts
admin/src/main/ts/app/users/details/sections/structures/user-structures-section.component.ts

Related to CAV2-181: https://opendigitaleducation.atlassian.net/browse/CAV2-181

Replace tooltip by native title attribute

---

workspace/src/main/resources/public/template/icons.html
workspace/src/main/resources/public/ts/delegates/actions/create.ts

Co-authored-by: Richard Bunel <richard.bunel@opendigitaleducation.com>
Le code ajouté est de Richard, j'ai seulement enlevé des lignes qu'il avait mise en trop

[Evo][Workspace] #22173 : removed owner name for own folder

---

conversation/src/main/resources/public/template/mail-actions/read-mail.html
conversation/src/main/resources/public/template/mail-actions/view-mail.html
conversation/src/main/resources/public/ts/controllers/controller.ts
conversation/src/main/resources/public/ts/model/mail.ts

Related to issue 22381: http://support.web-education.net/issues/22381

Fix conversation when mail contains invisible tags (style, comments, etc.)

---

admin/src/main/ts/app/users/details/sections/info/user-info-section.component.ts

Related to CAV2-226: https://opendigitaleducation.atlassian.net/browse/CAV2-226

Do not display the user creation date if unknown

---

admin/src/main/ts/app/app.routing.ts
admin/src/main/ts/app/core/store/abstract.store.ts
admin/src/main/ts/app/core/store/models/structure.model.ts
admin/src/main/ts/app/services/services.component.ts
admin/src/main/ts/app/services/services.routing.ts
admin/src/main/ts/app/services/services.store.ts
admin/src/main/ts/app/services/shared/services-list-with-companion.component.ts
admin/src/main/ts/app/services/shared/services-role-attribution.component.ts

Related to CAV2-374: https://opendigitaleducation.atlassian.net/browse/CAV2-374

Fix error on the services page of admin app

---

admin/src/main/ts/app/shared/ux/components/lightbox.component.ts

Related to issue CAV2-363: https://opendigitaleducation.atlassian.net/browse/CAV2-363

Fix lightbox on safari

---

common/src/main/java/org/entcore/common/bus/WorkspaceHelper.java
workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java
workspace/src/main/resources/i18n/fr.json
workspace/src/main/resources/public/template/toaster.html
workspace/src/main/resources/public/ts/controller.ts
workspace/src/main/resources/public/ts/delegates/lool.ts
workspace/src/main/resources/view-src/workspace.html

Add Libre Office Online integration

---

admin/src/main/ts/app/users/details/sections/duplicates/user-duplicates.section.component.ts
directory/src/main/java/org/entcore/directory/controllers/UserController.java

related to issue CAV2-67: https://opendigitaleducation.atlassian.net/browse/CAV2-67

[ODE] authorize adml to separate duplicate users if adml of one

---

admin/gulpfile.admin.js
admin/src/main/resources/i18n/fr.json
admin/src/main/resources/public/styles/admin.scss
admin/src/main/ts/app/shared/ux/components/panel-section.component.ts
admin/src/main/ts/app/users/communication/user-communication.component.ts
admin/src/main/ts/app/users/users.module.ts

Related to CAV2-385: https://opendigitaleducation.atlassian.net/browse/CAV2-385.

[ODE] integrate communication view in panel-section

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/app/groups/details/group-details.component.spec.ts
admin/src/main/ts/app/groups/details/group-details.component.ts
admin/src/main/ts/app/groups/groups.component.ts
admin/src/main/ts/app/users/communication/communication-rules.service.spec.ts
admin/src/main/ts/app/users/communication/communication-rules.service.ts
admin/src/main/ts/app/users/communication/group-card.component.spec.ts
admin/src/main/ts/app/users/communication/group-card.component.ts
build.gradle
communication/src/main/java/org/entcore/communication/controllers/CommunicationController.java
communication/src/main/java/org/entcore/communication/services/CommunicationService.java
communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
communication/src/test/java/org/entcore/communication/services/impl/DefaultCommunicationServiceTest.java

Related to CAV2-400: https://opendigitaleducation.atlassian.net/browse/CAV2-400.

[ODE] Check the group relationships before changing the internal communication rule of a group

---

portal/src/main/resources/i18n/fr.json

Just a fr.json key to translate i18n in zimbra console page.

Title of admin console page "outside communication"

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/app/users/communication/communication-rules.component.spec.ts
admin/src/main/ts/app/users/communication/communication-rules.component.ts
admin/src/main/ts/app/users/communication/communication-rules.service.spec.ts
admin/src/main/ts/app/users/communication/communication-rules.service.ts
admin/src/main/ts/app/users/communication/smart-user-communication.component.ts
admin/src/main/ts/app/users/communication/user-communication.component.spec.ts
admin/src/main/ts/app/users/communication/user-communication.component.ts
communication/src/main/java/org/entcore/communication/controllers/CommunicationController.java
communication/src/main/java/org/entcore/communication/services/CommunicationService.java
communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java

[ODE] show relations from the others groups to the user groups

---

admin/src/main/ts/app/core/resolvers/i18n.resolver.ts
admin/src/main/ts/app/core/store/models/application.model.ts
admin/src/main/ts/app/services/applications/application/smart-application.component.ts
admin/src/main/ts/app/services/shared/services-list.component.ts
app-registry/src/main/java/org/entcore/registry/services/impl/DefaultAppRegistryService.java
package.json

Related to #CAV2-276: https://opendigitaleducation.atlassian.net/browse/CAV2-276

[ODE] display application names as the portal does

---

admin/src/main/ts/app/core/store/models/user.model.ts
admin/src/main/ts/app/users/details/sections/classes/user-classes-section.component.ts
admin/src/main/ts/app/users/details/sections/duplicates/user-duplicates.section.component.ts

Related to issue CAV2-435: https://opendigitaleducation.atlassian.net/browse/CAV2-435.

[ODE] fix duplicate display after merging duplicated users

---

admin/src/main/ts/app/shared/ux/components/group-picker.component.spec.ts
admin/src/main/ts/app/shared/ux/components/group-picker.component.ts
admin/src/main/ts/app/users/communication/communication-rules.component.spec.ts
admin/src/main/ts/app/users/communication/communication-rules.component.ts
admin/src/main/ts/app/users/communication/smart-user-communication.component.ts
admin/src/main/ts/app/users/communication/user-communication.component.spec.ts
admin/src/main/ts/app/users/communication/user-communication.component.ts

related to: https://opendigitaleducation.atlassian.net/browse/CAV2-403

[ODE] multi etab in add comm rule group picker

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/app/groups/details/group-details.component.spec.ts
admin/src/main/ts/app/groups/details/group-details.component.ts
admin/src/main/ts/app/groups/groups.module.ts
admin/src/main/ts/app/groups/groups.service.spec.ts
admin/src/main/ts/app/groups/groups.service.ts
admin/src/main/ts/app/shared/utils/testing.ts

Related to: https://opendigitaleducation.atlassian.net/browse/CAV2-458

[ODE] delete manual group feature

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/app/users/details/sections/duplicates/user-duplicates.section.component.ts
admin/src/main/ts/app/users/smart-users-comparison.component.spec.ts
admin/src/main/ts/app/users/smart-users-comparison.component.ts
admin/src/main/ts/app/users/user-overview.component.spec.ts
admin/src/main/ts/app/users/user-overview.component.ts
admin/src/main/ts/app/users/user.service.spec.ts
admin/src/main/ts/app/users/user.service.ts
admin/src/main/ts/app/users/users-comparison.component.spec.ts
admin/src/main/ts/app/users/users-comparison.component.ts
admin/src/main/ts/app/users/users.module.ts

Related to CAV2-195: https://opendigitaleducation.atlassian.net/browse/CAV2-195.

[ODE] show a comparison view for duplicated users

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/app/communication/communication-rules.component.spec.ts
admin/src/main/ts/app/communication/communication-rules.component.ts
admin/src/main/ts/app/communication/communication-rules.service.spec.ts
admin/src/main/ts/app/communication/communication-rules.service.ts
admin/src/main/ts/app/communication/communication.module.ts
admin/src/main/ts/app/communication/group-card.component.spec.ts
admin/src/main/ts/app/communication/group-card.component.ts
admin/src/main/ts/app/communication/groups-communication.component.spec.ts
admin/src/main/ts/app/communication/groups-communication.component.ts
admin/src/main/ts/app/groups/communication/smart-group-communication.component.ts
admin/src/main/ts/app/groups/details/group-details.component.spec.ts
admin/src/main/ts/app/groups/details/group-details.component.ts
admin/src/main/ts/app/groups/details/group-details.resolver.ts
admin/src/main/ts/app/groups/groups.component.ts
admin/src/main/ts/app/groups/groups.module.ts
admin/src/main/ts/app/groups/groups.routing.ts
admin/src/main/ts/app/groups/groups.store.ts
admin/src/main/ts/app/groups/type-view/groups-type-view.component.ts
admin/src/main/ts/app/users/details/user-details.component.ts
admin/src/main/ts/app/users/details/user-details.resolver.ts
admin/src/main/ts/app/users/users.module.ts
admin/src/main/ts/app/users/users.resolver.ts
admin/src/main/ts/app/users/users.store.ts

Related to CAV2-93: https://opendigitaleducation.atlassian.net/browse/CAV2-93.

[ODE] adds communication rules view for a group

---

directory/src/main/resources/public/template/group-actions.html
directory/src/main/resources/public/template/user-actions.html
directory/src/main/resources/public/ts/controllers/directory.ts

Ajoute le bouton "envoyer un mail" via zimbra dans l'annuaire lors de la sélection d'un groupe ou d'un utilisateur

feat(directory): add button to send mail with zimbra

---

common/src/main/java/org/entcore/common/elasticsearch/ElasticSearch.java

Ajout des fonctionnalités suivantes:
- Modification d'une ressource
- Suppression d'une ressource
- Création avec un ID donné

feat(STS) Add ElasticSearch function (update, delete, create with id..)

---

auth/src/main/java/org/entcore/auth/controllers/SamlController.java
auth/src/main/java/org/entcore/auth/services/impl/SSOMatrix.java

- Add Saml2 SSO Matrix response
- Fix redirect to login if user is null during saml process

feat(Matrix) Add SSO Matrix

---

auth/src/main/java/org/entcore/auth/services/impl/SSOMatrix.java

Modification de la réponse SAML Matrix

fix(SAML) Update Matrix SSO response

---

cas/src/main/java/org/entcore/cas/services/ExplorateurDeMetiersRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Ajout d'un réponse CAS spécifique à Explorateur de Metiers.
Lié à : https://github.com/opendigitaleducation/springboard-plugin/pull/21

feat : Add response CAS for Explorateur de Metiers

---

cas/src/main/java/org/entcore/cas/services/SalvumRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Il faut créer la réponse CAS pour Salvum.
On est parti de la réponse English Attack auquelle on a rajouté la date de naissance.

feat(cas): Add Salvum cas

---

cas/src/main/java/org/entcore/cas/services/MilliwebRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Nous avons besoin de créer une réponse CAS pour Milliweb pour le 77.
Elle a été testé et validé par l'équipe technique de Milliweb.

feat(cas): Add new CAS response Milliweb

---

common/src/main/java/org/entcore/common/neo4j/Neo4jRest.java
infra/src/main/java/org/entcore/infra/Starter.java

Ajout de la configuration de la valeur SameSite du cookie. Va de pair avec la PR https://github.com/opendigitaleducation/web-utils/pull/6

feat(Auth) Configure SameSite cookie value

---

cas/src/main/java/org/entcore/cas/services/IjboxRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Nous avons besoin de créer une réponse CAS pour Ijbox pour IDF.

feat(cas): Add new CAS response Ijbox

---

common/src/main/java/org/entcore/common/http/filter/AppOAuthResourceProvider.java
directory/src/main/java/org/entcore/directory/controllers/UserController.java
directory/src/main/java/org/entcore/directory/services/UserService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java

Bonjour, 
Nous avons besoin de créer une oAuth passant moins d'informations à des services externes afin de se conformer au RGPD.
Cela se ferait à travers le passage du scope "myInfos-ext".

feat(directory): Add special oAuth myInfos scope for external services

---

feeder/src/main/java/org/entcore/feeder/csv/CsvValidator.java

- Fix : correction de la recherche d'élève lors de l'import CSV d'un Utilisateur extérieur lié à un élève sans classe

fix(feeder): DCN-89 Fix CSV import of relative linked to classless student

---

common/src/main/java/org/entcore/common/email/EmailFactory.java
gradle.properties

Va avec la PR sur web-utils https://github.com/opendigitaleducation/web-utils/pull/8

feat() Add SMTP support

---

app-registry/src/main/java/org/entcore/registry/controllers/AppRegistryController.java
app-registry/src/main/java/org/entcore/registry/controllers/ExternalApplicationController.java

- Ajout d'un évènement EventBus pour créer une application externe

feat(app-registry): Add create external application bus event

---

feeder/src/main/java/org/entcore/feeder/csv/CsvFeeder.java
feeder/src/main/java/org/entcore/feeder/dictionary/structures/Importer.java

- Ajout des élèves/parents aux groupes de fonctions créés après import CSV

fix(feeder): DCN-78 CSV import of students/relatives : add user to newly created functional group

---

admin/src/main/ts/src/app/app.component.ts

http://support.web-education.net/issues/45900
Suppression du chargement du hotjar depuis app.component.ts

[ODE] adminv2 : Supprimer le plugin hotjar

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.html
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.scss
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.ts
admin/src/main/ts/src/app/management/structure-informations/structure-informations.service.ts
directory/src/main/java/org/entcore/directory/controllers/StructureController.java
directory/src/main/java/org/entcore/directory/services/SchoolService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultSchoolService.java

Ajout d'une nouvelle route côté back, réservée aux ADMC, qui prend une liste d'UAI en paramètre et vérifie si les structures correspondantes existent.
Ajout d'une lightbox côté front et d'un service qui appelle cette nouvelle route.

[ODE] adminv2 : ajout d'un service pour vérifier les UAI qu'on s'apprête à paramétrer

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.html
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.ts
admin/src/main/ts/src/app/management/structure-informations/structure-informations.service.ts
app-registry/src/main/java/org/entcore/registry/controllers/AppRegistryController.java
app-registry/src/main/java/org/entcore/registry/services/AppRegistryService.java
app-registry/src/main/java/org/entcore/registry/services/impl/DefaultAppRegistryService.java
common/src/main/java/org/entcore/common/neo4j/TransactionHelper.java
directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
directory/src/main/java/org/entcore/directory/controllers/StructureController.java
directory/src/main/java/org/entcore/directory/services/SchoolService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultSchoolService.java

Implémentation de la duplication du paramétrage d'une structure témoin  en réutilisant les services existants et accessibles par le Bus.

[ODE] adminv2 : implémentation de la duplication de paramétrage dans le backend

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/users/details/sections/info/user-info-section.component.html
admin/src/main/ts/src/app/users/details/sections/info/user-info-section.component.ts

http://support.web-education.net/issues/45889
utilisation du composant "ode-lightbox-confirm", pas de difficultés à priori...

[ODE] adminv2 : Ajout d'un message de confirmation lors du passage d'un compte en ADML

---

admin/src/main/ts/src/app/core/nav/nav.component.html
admin/src/main/ts/src/app/core/nav/nav.component.ts
admin/src/main/ts/src/assets/admin.scss

Utilisation de la nouvelle propriété ajoutée à ode-item-tree pour afficher les UAI et modification du filtre appliqué pour rechercher par UAI en plus du nom.

[ODE] adminv2 : recherche par UAI

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/management/message-flash/form/message-flash-form/message-flash-form.component.html
admin/src/main/ts/src/app/management/message-flash/form/message-flash-form/message-flash-form.component.scss
admin/src/main/ts/src/app/management/message-flash/form/message-flash-form/message-flash-form.component.ts

[ODE] adminv2 : pouvoir (dé)sélectionner toutes les structures dans les messages flashs

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/core/store/collections/widget.collection.ts
admin/src/main/ts/src/app/core/store/models/structure.model.ts
admin/src/main/ts/src/app/core/store/models/widget.model.ts
admin/src/main/ts/src/app/services/services.module.ts
admin/src/main/ts/src/app/services/services.routing.ts
admin/src/main/ts/src/app/services/services.store.ts
admin/src/main/ts/src/app/services/shared/services-list/services-list.component.ts
admin/src/main/ts/src/app/services/widgets/list/widgets-list.component.html
admin/src/main/ts/src/app/services/widgets/list/widgets.resolver.ts
admin/src/main/ts/src/app/services/widgets/widget/smart-widget/smart-widget.component.html
admin/src/main/ts/src/app/services/widgets/widget/smart-widget/smart-widget.component.ts

http://support.web-education.net/issues/46832
affichage de la liste des widgets dans l'onglet widgets du module services

[ODE] adminv2 : liste des widgets

---

admin/src/main/ts/src/app/management/structure-informations/structure-informations.service.ts
app-registry/src/main/java/org/entcore/registry/controllers/AppRegistryController.java
app-registry/src/main/java/org/entcore/registry/services/AppRegistryService.java
app-registry/src/main/java/org/entcore/registry/services/impl/DefaultAppRegistryService.java
directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
directory/src/main/java/org/entcore/directory/controllers/StructureController.java
directory/src/main/java/org/entcore/directory/services/SchoolService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultSchoolService.java

Refactoring des requêtes neo4j de duplication de paramétrage afin d'améliorer les performances sur de gros volumes.

[ODE] adminv2 : refactoring des requêtes neo4j de duplication de paramétrage

---

admin/src/main/ts/src/app/core/nav/nav.component.ts
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.html
admin/src/main/ts/src/app/management/structure-informations/structure-informations.component.ts
directory/src/main/resources/public/ts/admin/delegates/menu.ts
directory/src/main/resources/view-src/class-admin.html

+ Recherche adminv2 insensible à la casse et aux accents

[ODE] adminv2 : Retours de recette source d'alimentation

---

cas/src/main/java/org/entcore/cas/services/DefaultRegisteredService.java
cas/src/main/java/org/entcore/cas/services/PmbRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Bonjour, 
Nous avons besoin de créer une réponse CAS spécifique pour Pmb qui va interroger le module pmb-connector.

feat(cas): Add new CAS response for Pmb

---

workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java

Fix list() function for eventBus action "list"

fix(Workspace) Fix list eventbus

---

workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java
workspace/src/main/java/org/entcore/workspace/security/WorkspaceResourcesProvider.java
workspace/src/main/resources/i18n/fr.json
workspace/src/main/resources/public/template/directives/file-viewer.html
workspace/src/main/resources/public/template/toaster.html
workspace/src/main/resources/public/ts/controller.ts
workspace/src/main/resources/public/ts/delegates/scratch.ts
workspace/src/main/resources/public/ts/directives/fileViewer.ts
workspace/src/main/resources/view-src/workspace.html

Bonjour, 
Pour la Normandie, nous avons besoin d'ouvrir des projets scratch dans l'espace documentaire sur un éditeur Scratch comme pour Lool.
Pouvez-vous accepter cette PR rapidement svp ?

feat(scratch): Open scratch file in scratch platform

---

cas/src/main/java/org/entcore/cas/services/EnseignoRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json
directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java

Bonjour,
Nous avons besoin de créer une réponse CAS spécifique pour Enseigno qui fonctionne aussi pour le 1D et 2D, retournant seulement les informations nécessaires à la plateforme.

feat(cas): Add new CAS response Enseigno

---

workspace/src/main/resources/view-src/workspace.html

Simple ajout d'un second boutton snippet pour accéder à l'application Lool et ajout d'une source à ces deux boutons pour mieux les gérer dérrière.

feat(Lool): [LOOL-24] Add button creation document in workspace (WIP)

---

directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java

Bonjour,
Nous avons besoin de livrer un correctif sur le scope oAuth myinfos. Cela permettrait d'homogénéiser les fonctions de l'utilisateur dans la réponse oAuth. Cette version correctif ne présente pas de risques, ni d'impact.

fix(myinfos): return the user functions properly

---

cas/src/main/java/org/entcore/cas/services/AtNormandieRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Bonjour,
Nous avons besoin de créer une réponse CAS spécifique pour Atout Normandie, retournant seulement les informations nécessaires à la plateforme.

feat(cas): CO-1620 add AtoutNormandie cas

---

auth/src/main/java/org/entcore/auth/controllers/SamlController.java
auth/src/main/java/org/entcore/auth/security/SamlValidator.java

Cette feature a pour but de rajouter dans le Protocol SAML une réponse "InResponseTo"
Dans notre service externe (Nextcloud par exemple), nous utilisons SAML pour le SSO et ce dernier a besoin du field "InResponseTo"

feat(saml): #DRIV-33 add new field InResponseTo SAML's response

---

auth/src/main/java/org/entcore/auth/security/SamlValidator.java

Cette PR reprend https://github.com/opendigitaleducation/entcore/pull/275 et https://github.com/opendigitaleducation/entcore/pull/274
Sur certains service externe (Riot Synapse Matrix), il est nécessaire de positionner le "InResponseTo" dans la réponse dans le champ "subjectConfirmationData"
`i:type="xs:string">NOM EXEMPLE</ns1:AttributeValue></ns1:Attribute></ns1:AttributeStatement></ns1:Assertion></ns0:Response>
2022-04-06 16:21:03,730 - saml2.response - 532 - ERROR - POST-40 - Unsolicited response id-jUhyAdaejRPds2Qbs
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/saml2/entity.py", line 1144, in _parse_response
response = response.loads(xmlstr, False, origxml=xmlstr)
File "/usr/local/lib/python3.7/site-packages/saml2/response.py", line 522, in loads …

feat(saml): #DRIV-33 add extra "InResponseTo" to subjectConfData field

---

admin/src/main/ts/src/app/core/store/models/userdetails.model.ts

pouvoir mettre un professeur, professeur principal.

fix(admin): EVAL-92 fix condition to add Head Teacher on User

---

directory/src/main/java/org/entcore/directory/Directory.java
directory/src/main/java/org/entcore/directory/controllers/SubjectController.java
directory/src/main/java/org/entcore/directory/services/SubjectService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultSubjectService.java
feeder/src/main/java/org/entcore/feeder/Feeder.java
feeder/src/main/java/org/entcore/feeder/ManualFeeder.java
feeder/src/main/java/org/entcore/feeder/dictionary/structures/Subject.java

add external id on manual subject
move create, update and delete methods in feeder
no impact

fix(directory) : Eval 221 add external id on manual subject

---

workspace/src/main/resources/public/ts/delegates/geogebra.ts
workspace/src/main/resources/public/ts/directives/fileViewer.ts

Bonjour,
Nous avons besoin de cette PR afin de corriger les urls de redirection vers le module geogebra depuis le workspace svp.
Impacts/Risques : 0

fix(geogebra) : #MEX-197 change url redirection geogebra

---

build-m1.sh
common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginCommunicationRedis.java
test/src/main/java/org/entcore/test/DatabaseTestHelper.java

Assurer le fait que les messages soient toujours poussés dans le bon ordre sur Redis pour assurer que le traitement des événements dans le bon ordre chronologique côté batch d'ingestion.

feat(explorer): crash recovery

---

directory/src/main/resources/view-src/text/exportEsidoc.id.txt

Added address, zipcode and city in esidoc export

fix(directory): #CO-1607 add address in esidoc export

---

cas/deployment/cas/conf.j2
cas/src/main/java/org/entcore/cas/services/ElmsRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Bonjour,
Nous avons besoin de créer une réponse CAS spécifique pour eLMS qui va interroger le module gar-connector.
Merci d'avance !

feat(cas): #CO-1701 add eLMS service cas

---

admin/src/main/ts/src/app/imports-exports/mailing/mass-mail/mass-mail.component.html

Sur le template admin de la console d'administration, ajout de la barre de recherche sur le multi-combo des classes.
(Désormais, tous les multi-combo de cette page suivent donc la même logique que ceux de la page des users).

feat(admin-mass-mail): #DCN-230 add filter search on classes multi-combo selector (on mass-mail template).

---

session/src/main/java/org/entcore/session/AuthManager.java

Lorsque l'implémentation Redis des sessions est utilisée, la validation du numéro de téléphone ne valide pas automatiquement le MFA pour la session en cours.
Ce problème est dû au fait que l'implémentation de session-redis supprime l'entrée `cache` des sessions lors de leur premier enregistrement dans Redis (appel à `RedisSessionStore.putSession` fait un `infos.remove(CACHE);`.
En l'absence de plus d'informations sur la raison de l'existence de ce `remove`, la solution retenue consiste à ajouter les attribtuts de cache de l'ancienne session après le `putSession` si l'ancien cache n'est pas vide.
WB-1669
Même test que décrit dans le ticket.
- Performance …

[ODE] fix(session): populate session's cache after recreating a session

---

build.gradle
common/src/main/java/org/entcore/common/explorer/ExplorerMessage.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerFolderTree.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerFolderTreeMongo.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerFolderTreeSql.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerPlugin.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginResourceMongo.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginResourceSql.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResource.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResourceMongo.java
common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResourceSql.java
gradle.properties

Ce commit corrige deux choses:
- les infos concernant le créateur
- l'acquittement des messages en lot dans pg
Les informations concernant le créateur n'était pas forcément cohérente car elles se basaient sur l'utilisateur qui envoie le message. Or si le message existe déjà dans l'application émettrice mais pas dans elastic search alors l'utilisateur qui met à jour la ressource devient le propriétaire (et la date de création est incorrect).
L'acquittement en lot des ressources ingérées génèraient une erreur:
`io.vertx.core.impl.NoStackTraceThrowable: The number of parameters to execute should be consistent with the expected number of parameters = [3] but the actual number is [18].
`
Ticket JIRA : [WB2-601](https://opendigitaleducation.atlassian.net/browse/WB2-601)
Please check options …

fix: #WB2-601, manage creatorId and pg bulk ack

---

directory/src/main/java/org/entcore/directory/controllers/UserController.java
directory/src/main/resources/jsonschema/updateUser.json

In order to increase security on the endpoint dedicated to update user's data, a control through json schema on the request's body is performed.
The json schema works here as a whitelist of fields entitled to be present in request's body.
https://opendigitaleducation.atlassian.net/browse/WB-1386
Tests and API documentation performed with Postman :
- Valid body : https://odedev.postman.co/workspace/ODE-Workspace-!-%25F0%259F%2594%25A5~4a0fc722-abd3-4ab5-8193-3d1c44b1540c/example/19647904-4f62f7de-ea93-467b-88ed-cea9e3564ca4
- Invalid body : https://odedev.postman.co/workspace/ODE-Workspace-!-%25F0%259F%2594%25A5~4a0fc722-abd3-4ab5-8193-3d1c44b1540c/example/19647904-c5d7fe8b-cfc9-4ee3-b7be-83ed25025073 …

User update control

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/users/details/sections/duplicates/user-duplicates.section.component.html

Lors du clic sur "Fusionner les doublons" en console d'admin une modale de confirmation s'ouvre. Lorsqu'on la quitte en cliquant à l'extérieur ou sur annuler il ne faut pas que la fusion se fasse.
Cette PR consiste donc en la modification du comportement de la modale de confirmation qui maintenant présente 3 boutons :
- Annuler, qui ferme juste la modale et ne déclenche aucune action (tout comme le clic à l'extérieur de la modale)
- "Ne pas conserver", qui déclenche la fusion sans conservation des rattachements
- "Conserver", qui déclenche la fusion avec conservation des rattachements
WB-1937
1. Avoir 2 comptes en doublon
2. Cliquer sur "fusionner"
3. Cliquer à l'extérieur de la modale
4. Rafraîchir …

[ODE] Ne pas fusionner les comptes dupliqués si on ne l'a pas confirmé

---

admin/src/main/ts/src/assets/_apps-connectors.scss
admin/src/main/ts/src/assets/_apps.scss

Ajout de l'icone emploi du temp dans entcore
Ticket : #WB2-916
https://edifice-community.atlassian.net/jira/software/c/projects/WB2/boards/41?modal=detail&selectedIssue=WB2-916&assignee=712020%3A10bcae25-bc57-4d87-bad7-d00cf4320f32

feat: #WB2-916, add icon edt in entcore

---

directory/src/test/java/org/entcore/directory/org/entcore/directory/services/impl/DefaultUserServiceTest.java
test/src/main/java/org/entcore/test/preparation/ClassTest.java
test/src/main/java/org/entcore/test/preparation/DataHelper.java
test/src/main/java/org/entcore/test/preparation/Function.java
test/src/main/java/org/entcore/test/preparation/GroupTest.java
test/src/main/java/org/entcore/test/preparation/GroupTestBuilder.java
test/src/main/java/org/entcore/test/preparation/Profile.java
test/src/main/java/org/entcore/test/preparation/StructureTest.java
test/src/main/java/org/entcore/test/preparation/StructureTestBuilder.java
test/src/main/java/org/entcore/test/preparation/UserBookTest.java
test/src/main/java/org/entcore/test/preparation/UserBookTestBuilder.java
test/src/main/java/org/entcore/test/preparation/UserTest.java
test/src/main/java/org/entcore/test/preparation/UserTestBuilder.java

Implémentation des TUs et des TIs pour couvrir la route /directory/myinfos.
Pour ce faire, une classe `DataHelper` a été créée et met à disposition de quoi peupler la base. L'introduction de cette classe permet l'écriture plus facile des tests et en facilite la lecture.
WB-2138 

[ODE][Tests] Implémentation des TUs et des TIs pour couvrir la route /directory/myinfos

---

auth/src/main/java/org/entcore/auth/services/impl/SSOJira.java

On a ajouté la connexion SSO à Jira via un event bus. Cet event bus se trouve dans un module à part (https://github.com/OPEN-ENT-NG/jira-connector).
Cela permettra de maintenir le code plus simplement en l'externalisant.
https://jira.support-ent.fr/browse/MEX-304
1. Se connecter à Jira via SSO
2. Vérifier que les informations fournies tel que l'utilisateur ou les groupes sont bien renseigné dans le profil
3. Vérifier que les tickets attribués correspondent bien aux groupes attribués

feat(sso-jira): #MEX-304 add event bus call for sso jira (#8)

---

directory/src/main/java/org/entcore/directory/security/DirectoryResourcesProvider.java

Donner accès à la route /directory/group/admin/funcAndDisciplines aux ADMLs (seuls les ADMCs avaient alors accès à cette route).
Le changement consiste en :
- la modification de DirectoryResourcesProvider pour ajouter la méthode `getFuncGroups` à la vérification `isAdminOfStructureOrClass`
- la création d'une surcharge de `isAdminOfStructureOrClass` qui prend en paramètre le structureId et classId qui proviennent soit du corps de la requête, soit des _query params_
[WB-2235](https://edifice-community.atlassian.net/browse/WB-2235)
1. Se connecter avec un utilisateur non ADML (simon.briaud)
2. Tenter d'accéder à la route http://localhost:8090/directory/group/admin/funcAndDisciplines?structureId=18792e9f- …

[EDIFICE] Donner accès à la route /directory/group/admin/funcAndDisciplines aux ADMLs

---

cas/src/main/java/org/entcore/cas/services/WebGerestRegisteredService.java

Update CAS response service for WebGerest
https://jira.support-ent.fr/browse/COE-20

feat(WebGerest): [#COE-20] update CAS response for WebGerest service

---

auth/src/main/resources/public/ts/validate-mail/directives/navbar-legacy.directive.ts

Change display for welcome key I18n for displayName to firstname
https://edifice-community.atlassian.net/browse/WB-2026

Fix: #WB-2026, Change display to firstname for welcome key i18n

---

cas/src/main/java/org/entcore/cas/services/SmartSchoolRegisteredService.java

We have 4 different user groups on Computer 3 for which we must associate these Drupal roles:
Functional Administrator
Industrial Partner
DF user
=> All the other roles already present in smartschool are associated with specific rights (see table on confluence)
We must adapt the CAS smartschool response to export the Drupal role according to the profile and functions of the user.
[DCN-315](https://jira.support-ent.fr/browse/DCN-315)
Create a structure with the name "Digitale Factory"
Create a function with the name "ministrypartner"
Create the following users in the structure:
- User 1: with the local admin function
- User 2: invite with the ministrypartner function
- User 3: invite
Call the …

feat(cas): #DCN-315 adapted from smartschool's CAS response (#7)

---

cas/src/main/java/org/entcore/cas/services/SmartSchoolRegisteredService.java
common/src/main/java/org/entcore/common/http/filter/AppOAuthResourceProvider.java
directory/src/main/java/org/entcore/directory/controllers/UserController.java
directory/src/main/java/org/entcore/directory/services/UserService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java

Add a new service for Saooti oAuth connector
https://jira.support-ent.fr/browse/COE-21

feat(oAuth): #COE-21 add Saooti oAuth connector

---

cas/src/main/java/org/entcore/cas/services/WebGerestRegisteredService.java

Fix CAS response service for WebGerest
https://jira.support-ent.fr/browse/COE-20

fix(WebGerest): [#COE-20] fix CAS response for WebGerest service

---

directory/src/main/resources/public/template/user-edit.html
directory/src/main/resources/public/template/user-view.html

https://edifice-community.atlassian.net/browse/MOZO-79

fix(directory): MOZO-79 fix alignment in user profile

---

admin/src/main/resources/i18n/fr.json
admin/src/main/ts/src/app/groups/groups/groups.component.ts

Feat: #WB-634 BoardcastGroup Update wording, update tab display rule.
Add feedback from [ticket WB-634](https://edifice-community.atlassian.net/browse/WB-634?focusedCommentId=39587) 

Feat: #WB-634 BoardcastGroup Update wording, update tab display rule.

---

common/src/main/java/org/entcore/common/http/EntAccessLogger.java

Add user information in access logs for logout requests
[WB-2299](https://edifice-community.atlassian.net/browse/WB-2299)
[WB-2299]: https://edifice-community.atlassian.net/browse/WB-2299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EDIFICE] Add user information in access logs for logout requests

---

tests/src/test/scenarios/cucumber.js
tests/src/test/scenarios/features/functions.feature
tests/src/test/scenarios/features/step_definitions/stepdefs.js
tests/src/test/scenarios/libs/api.js
tests/src/test/scenarios/libs/env.js
tests/src/test/scenarios/libs/structure-api.js
tests/src/test/scenarios/libs/user-api.js
tests/src/test/scenarios/package.json

Test de la fonctionnalité d'ajout de fonctions à un utilisateur

[Edifice] Test de la fonctionnalité d'ajout de fonctions à un utilisateur

---

workspace/src/main/resources/view-src/workspace.html

Feat wb 2247 update lool actions display

---

common/src/main/java/org/entcore/common/sms/SmsSender.java

WB-2220 function to send message to phone number

---

directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java

fix Saooti response to show the full function name
[CS-4](https://jira.support-ent.fr/browse/CS-4)
1. Connect with a user
2. GET Request on the "directory/saooti" endpoint
3. In the response, you should get the full name of the function from the user

fix(oAuth): #CS-4 fix Saooti response

---

common/src/main/java/org/entcore/common/share/impl/MongoDbShareService.java
gradle.properties

Ce commit ajoute des read preferences configurable sur les méthodes: find/findOne/count
#WB2-1421
- [ X] Bug fix (PATCH)
- [ X] common
- [ X] All done ! :smiley:

fix: #WB2-1421, sync shares using primary db

---

audience/src/main/java/org/entcore/audience/reaction/dao/impl/ReactionDaoImpl.java
audience/src/main/java/org/entcore/audience/reaction/model/ReactionsSummary.java
audience/src/test/java/org/entcore/audience/reaction/service/impl/DumbSQL.java
audience/src/test/java/org/entcore/audience/reaction/service/impl/ReactionServiceImplTest.java
audience/src/test/resources/initAudience.sql
build.gradle
common/src/main/java/org/entcore/common/sql/SqlResult.java
test/src/main/java/org/entcore/test/DatabaseTestHelper.java

Mise en place des TUs sur la partie réucpération du résumé des réactions du service de gestion des réactions.

test: #WB-2576, unit tests

---

common/src/main/java/org/entcore/common/controller/ControllerHelper.java
common/src/main/java/org/entcore/common/share/ShareNormalizer.java

Ce commit ajoute un helper permettant de bénéficier des droits normalisés sur une application.
#Wb2-1400
- [X ] New feature (MINOR)
- [ X] common
- [X ] All done ! :smiley:

[EDIFICE] feat: #Wb2-1400, add normalize rights helper

---

audience/src/main/gradle.properties
audience/src/main/java/org/entcore/audience/services/impl/EventBusAudienceAccessFilter.java
common/src/main/java/org/entcore/common/audience/to/AudienceCheckRightRequestMessage.java

Mise à jour du message de vérification des droits sur des posts avec les ids des groupes de l'utilisateur.
PR liée :
https://github.com/edificeio/blog/pull/58
https://edifice-community.atlassian.net/browse/WB-2582

Feat wb 2582 check audience access rights

---

audience/src/main/java/org/entcore/audience/Audience.java
audience/src/main/java/org/entcore/audience/controllers/AudienceController.java
audience/src/main/java/org/entcore/audience/reaction/dao/ReactionDao.java
audience/src/main/java/org/entcore/audience/reaction/dao/impl/ReactionDaoImpl.java
audience/src/main/java/org/entcore/audience/reaction/service/ReactionService.java
audience/src/main/java/org/entcore/audience/reaction/service/impl/ReactionServiceImpl.java
audience/src/main/java/org/entcore/audience/services/AudienceService.java
audience/src/main/java/org/entcore/audience/services/impl/AudienceServiceImpl.java
audience/src/main/java/org/entcore/audience/view/dao/ViewDao.java
audience/src/main/java/org/entcore/audience/view/dao/ViewDaoImpl.java
audience/src/main/java/org/entcore/audience/view/service/ViewService.java
audience/src/main/java/org/entcore/audience/view/service/impl/ViewServiceImpl.java
audience/src/test/java/org/entcore/audience/reaction/service/impl/ReactionServiceImplTest.java
audience/src/test/java/org/entcore/audience/view/service/impl/ViewServiceImplTest.java
common/src/main/java/org/entcore/common/audience/AudienceHelper.java
common/src/main/java/org/entcore/common/audience/to/NotifyResourceDeletionMessage.java
common/src/main/java/org/entcore/common/audience/to/NotifyResourceDeletionResponseMessage.java
common/src/main/java/org/entcore/common/sql/Sql.java

Implementation des cas de purge pour Audience :
- suppression d'utilisateurs
- fusion d'utilisateurs
- suppression de ressources
https://edifice-community.atlassian.net/browse/WB-2569

WB-2569 purge audience

---

audience/src/main/java/org/entcore/audience/controllers/AudienceController.java

Adaptation de l'annotation Trace pour gérer l'absence de body.
https://edifice-community.atlassian.net/browse/WB-2636

fix: wb-2636, body absence handling

---

common/src/main/java/org/entcore/common/share/impl/GenericShareService.java
tests/src/test/js/stresstest/scenarios/workspace/share.js

WB-2242
Integration test in `tests/src/test/js/stresstest/scenarios/workspace/share.js`.

[EDIFICE] better handling of shares update based on users visibility

---

auth/src/main/java/org/entcore/auth/services/impl/SSOPeertube.java

We want to verify if the user has access to the peertube connector before creating an account with the SAML peertube plugin. We thus added a field in the SSO Peertube answer to retrieve this information in peertube. The field will be set to 'true' if the user has access to the application, or 'false' otherwise
[MEX-347](https://jira.support-ent.fr/browse/MEX-347)
With an account that has access to the connector, make an SSO request to the SSOPeertube response, check in the response if the 'hasConnectorAccess' field is properly filled and has the value 'true'. The same test can be performed with an account that does not have access to the …

feat(peertube-saml): #MEX-347 Add a field to the SSO response to indicate whether the user has access to the app

---

common/src/main/java/org/entcore/common/http/filter/MandatoryUserValidationFilter.java
docker-compose.yml

Remove test on header.
WB-2692

[EDIFICE] WB-2692

---

auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java

Création d'un historique de mot de passe dans le champ oldPasswords du noeud User et vérification del'absence d'un nouveau mot de passe dans cette liste lorsque l'utilisateur tente de changer de mot de passe.
WB-2755

[EDIFICE] Check that a password has not already been used when a user changes their password

---

directory/src/main/resources/public/template/dominos.html

Change wording for users search when no results found.
https://edifice-community.atlassian.net/browse/MOZO-157
- Se connecter avec un compte 1D
- Aller dans la vue "La classe"
- Lancer une recherche par nom d'utilisateur inexistant
- Vérifier que le wording et l'illustration correspondent à la spéc

feat(directory): #MOZO-157, change wording for users search when no results found

---

directory/src/main/resources/public/template/mono-class.html

Hide other users cards when displaying a user detail.
https://edifice-community.atlassian.net/browse/MOZO-158
- Se connecter avec un compte 1D
- Aller dans la vue "La classe"
- Sélectionner un utilisateur pour afficher sa fiche
=> La liste des utilisateurs ne doit pas s'afficher à gauche, et la fiche utilisateur prend toute la largeur de l'écran

feat(directory): #MOZO-158, hide other users cards when displaying a user detail

---

cas/src/main/java/org/entcore/cas/services/WebGerestRegisteredService.java

Just fix functions of Web Gerest
[CS-24](https://jira.support-ent.fr/browse/CS-24)
Create multiple profile who have the good functions, and test it in POSTMAN

fix(webgerest): #CS-24 fix functions to web gerest

---

auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java
auth/src/test/java/org/entcore/auth/UserAuthAccountTest.java

Création d'un historique de mot de passe dans le champ oldPasswords du noeud User et vérification del'absence d'un nouveau mot de passe dans cette liste lorsque l'utilisateur tente de changer de mot de passe.
WB-2755

 [EDIFICE] Check that a password has not already been used when a user changes their password

---

auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java

[EDIFICE] Store initial password after actvation in oldPasswords

---

portal/src/main/resources/i18n/fr.json

Change workspace public folder name i18n
https://edifice-community.atlassian.net/browse/WB-2753

fix(portal): #WB-2753, change workspace public folder name

---

auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
common/src/main/java/org/entcore/common/datavalidation/DataValidationService.java
common/src/main/java/org/entcore/common/datavalidation/EmailValidation.java
common/src/main/java/org/entcore/common/datavalidation/UserValidationService.java
common/src/main/java/org/entcore/common/datavalidation/impl/DefaultUserValidationService.java
common/src/main/java/org/entcore/common/user/UserInfos.java
directory/src/main/java/org/entcore/directory/controllers/UserController.java
directory/src/main/resources/i18n/fr.json
directory/src/main/resources/view-src/email/emailUpdateWarning.html
session/src/main/java/org/entcore/session/AuthManager.java

If the user's email address has been modified by any means, an email must be sent to their old email address.
https://edifice-community.atlassian.net/browse/MOZO-160
1. Se connecter avec un compte (peut importe le profil)
2. Aller sur la page "Mon compte"
3. Modifier l'adresse courriel
=> Après validation du code et confirmation, l'utilisateur doit recevoir un mail d'alerte sur son ancienne adresse mail lui information que son adresse mail a été modifiée.

feat: #MOZO-160, send warning email to old email address when it has been modified

---

auth/src/main/java/org/entcore/auth/services/impl/SSOGLPI.java

Handle case where academic mail is not available. Then it use the mail od the user.
CS-7 : https://jira.support-ent.fr/browse/CS-7

fix(GLPI): [#CS-7] add email to GLPI response

---

directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java

fix: #WB-3253, remove old passwords hashes from api response

---

admin/src/main/ts/src/app/_shared/user-position-list/user-position-list.component.html
admin/src/main/ts/src/app/_shared/user-position-list/user-position-list.component.ts
admin/src/main/ts/src/app/core/store/models/userdetails.model.ts
admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.html
admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.scss
admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.ts
admin/src/main/ts/src/app/users/details/user-details.component.html
admin/src/main/ts/src/app/users/details/user-details.component.ts
common/src/main/java/org/entcore/common/user/UserUtils.java
communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
directory/src/main/resources/public/ts/controllers/directory.ts

fix: WB-3123 request param to body, emptyscreen

---

admin/src/main/ts/src/app/_shared/user-position-list/user-position-list.component.html
admin/src/main/ts/src/app/_shared/user-position-list/user-position-list.component.ts
admin/src/main/ts/src/app/core/store/models/userPosition.model.ts
admin/src/main/ts/src/app/users/create/user-create.component.html
admin/src/main/ts/src/app/users/create/user-create.component.ts
admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.html
admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.ts
common/src/main/java/org/entcore/common/user/position/UserPositionService.java
common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
directory/src/main/java/org/entcore/directory/Directory.java
directory/src/main/java/org/entcore/directory/controllers/ClassController.java
directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
directory/src/main/java/org/entcore/directory/controllers/UserController.java
directory/src/main/java/org/entcore/directory/controllers/UserPositionController.java
directory/src/main/java/org/entcore/directory/services/UserService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
feeder/src/main/java/org/entcore/feeder/Feeder.java
feeder/src/main/java/org/entcore/feeder/ManualFeeder.java
tests/src/test/js/it/scenarios/position/attribute-position.js
tests/src/test/js/it/scenarios/position/crud.js

[EDIFICE] recherche insensibles à la casse + sécurité sur l'attribution des fonctions

---

auth/src/main/java/org/entcore/auth/controllers/AuthController.java
directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
directory/src/main/java/org/entcore/directory/controllers/SlotProfileController.java
directory/src/main/java/org/entcore/directory/controllers/TenantController.java
directory/src/main/java/org/entcore/directory/controllers/UserController.java
infra/src/main/java/org/entcore/infra/controllers/MonitoringController.java
infra/src/main/resources/public/js/lib.js

Reworking anti csrf filters
https://edifice-community.atlassian.net/browse/WB-3104
Appel des points d'entrée (en particulier depuis la console d'admin v1), pas de souci d'authentification via le XSRF token

Fix rework csrf filters

---

cas/src/main/java/org/entcore/cas/services/SmartSchoolRegisteredService.java

- [ x] Bug fix (PATCH)
- [ x] cas
- [ x] All done ! :smiley:

fix(smartschool): #DCN-495 DCN-504 fix multiple rights for campus and DF

---

auth/src/main/java/org/entcore/auth/controllers/AuthController.java
gradle.properties

https://edifice-community.atlassian.net/browse/INTEG-529

Integ 529 correction de la regression concernant la creation des sessions utilisateur sur la route post oauth 2 token

---

common/src/main/java/org/entcore/common/utils/DateUtils.java
gradle.properties

[EDIFICE] Add local date time formatter

---

feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java

Fix pour exécuter correctement la purge des fonctions CSV dans le cas d'une transition d'année.
https://edifice-community.atlassian.net/browse/WB-3415
Tests dev manuel en local : exécution d'un import CSV avec option de transition d'année.

fix : WB-3415, fix CSV import with year transition

---

common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java

On a identifié un exemple d'ADML correctement paramétré, qui n'a pas le droit de créer des Fonctions sur une structure précise sur lequel il a normalement les droits.
Ce fix consiste à aligner les requêtes de vérification des droits de l'utilisateur sur les structures au sein de l'ENT.
[Ticket WB-3940](https://edifice-community.atlassian.net/browse/WB-3490)
IT tests OK

fix(common): #WB-3940, better ADML function checking

---

cas/deployment/cas/conf.j2
cas/src/main/java/org/entcore/cas/services/OdeRegisteredService.java
cas/src/main/resources/i18n/en.json
cas/src/main/resources/i18n/fr.json

Add a new CAS response service for ODE
https://jira.support-ent.fr/browse/CS-25

feat(ode): [#CS-25] add new response CAS for ODE service

---

infra/src/main/java/org/entcore/infra/services/impl/MongoDbEventStore.java

Fix mongo parsing query error because with the new driver, dates are to be specified as string and not long.
1. curl 'http://xxxx:8001/infra/event/mark/traces/1736344800000?duration=3600000'
2. curl 'http://xxxx:8001/infra/event/mark/events/1736344800000?duration=3600000'

fix: use new date formatting for new mongodb driver

---

cas/src/main/java/org/entcore/cas/services/OdeRegisteredService.java

Fix NPE when dealing with a user having no function at all
CS-25 : https://jira.support-ent.fr/browse/CS-25

fix(ode): [#CS-25] fix ODE cas response when no functions exist

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/features/Message/message-attachments.test.tsx
conversation/frontend/src/features/Message/message-attachments.tsx
conversation/frontend/src/features/Message/message-header.tsx
conversation/frontend/src/features/Message/message-preview.test.tsx
conversation/frontend/src/mocks/index.ts
conversation/frontend/src/models/attachment.ts
conversation/frontend/src/routes/pages/message-display.tsx

Add attachment section on message detail

feat(conversation): #WB-3825 message attachments

---

conversation/frontend/src/features/Message/message-list.tsx
conversation/frontend/src/routes/pages/message-display.tsx
conversation/frontend/src/routes/root/index.css
conversation/frontend/src/services/queries/folder.ts
conversation/frontend/src/services/queries/message.ts

#WB-3855 update folder counter + small UI fix

feat(conversation): #WB-3855 refacto folder counter + markRead when show details + small UI fix

---

directory/src/main/resources/public/template/admin/user-list.html

#WB-3728 add relatives to student list

feat(class-admin): #WB-3728 add relatives to student list

---

directory/src/main/resources/i18n/fr.json
directory/src/main/resources/public/template/admin/user-infos.html
directory/src/main/resources/public/ts/admin/delegates/userCreate.ts
directory/src/main/resources/public/ts/admin/delegates/userInfos.ts

feat(class-admin): #WB-3774 add relative in student info modal

feat(class-admin): #WB-3774 add relative in student info modal

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/components/DisplayActionDropDown.tsx
conversation/frontend/src/routes/pages/message-display.tsx

feat(conversation): #WB-3826 display action list on message detail view

---

directory/src/main/resources/public/template/admin/create-user/form.html
directory/src/main/resources/public/template/admin/user-infos.html
directory/src/main/resources/public/ts/admin/delegates/userInfos.ts
directory/src/main/resources/public/ts/directives/intlPhoneInput.ts

feat(class-admin): #WB-3882 international number in user info page

---

common/src/main/java/org/entcore/common/service/impl/AbstractRepositoryEvents.java
common/src/main/java/org/entcore/common/storage/impl/GridfsStorage.java

Correction d'une erreur qui s'est introduite lors de la migration Vertx4
WB2-2501

fix: #WB2-2501, fix mongo query to find documents to export

---

auth/src/main/resources/public/template/activation-form.html
auth/src/main/resources/public/ts/app.ts
auth/src/main/resources/public/ts/controllers/activation.ts
auth/src/main/resources/public/ts/directives/intlPhoneInputNg.ts
auth/src/main/resources/public/ts/validate-mail/directives/intl-phone-input.directive.ts
auth/src/main/resources/public/ts/validate-mail/services/intl-phone-input.config.ts

Add international input number in activation account and profile. Update default config for internation number.

feat(auth): #WB-3888 international phone input auth module

---

conversation/frontend/src/components/DisplayActionDropDown.tsx

Feat(conversation): WB-3878 restore action on detail view

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/features/message/MessageHeader.tsx

show cci if current user is sender

feat(conversation): #WB-3881 show cci if current user is sender

---

conversation/frontend/src/components/DisplayActionDropDown.tsx

feat(conversation): #WB-3816 move to trash on detail message

---

conversation/frontend/src/components/DisplayActionDropDown.tsx

fix(conversation): #WB-3446, display reply all only necessary in message detail view

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/components/DisplayActionDropDown.tsx
conversation/frontend/vite.config.ts

feat(conversation): #WB-3437 save draft

---

conversation/frontend/src/components/DisplayActionDropDown.tsx
conversation/frontend/src/components/MessageBody.tsx
conversation/frontend/src/features/message-edit/index.tsx
conversation/frontend/src/features/message-list/index.tsx
conversation/frontend/src/routes/index.tsx
conversation/frontend/src/routes/pages/MessageEdit.tsx
conversation/frontend/src/services/api/messageService.ts
conversation/frontend/src/services/queries/message.ts
conversation/frontend/src/store/actions.ts
conversation/frontend/vite.config.ts

feat(conversation): #WB-3444 auto save draft

---

conversation/frontend/src/components/DisplayActionDropDown.tsx

Bouton retirer du dossier depuis la vue détail d'un message

feat(conversation): #WB-3461 remove from folder on view detail

---

conversation/frontend/src/components/DisplayActionDropDown.tsx
conversation/frontend/src/services/queries/message.ts

feat(conversation): #WB-3452 move to folder on view detail

---

conversation/frontend/src/components/MessageRecipientList/MessageRecipientList.tsx

Regle respectée :
À : / Cc : / Cci => partout sauf 1D détails d’un message =>  À : / Copie à : / Copie cachée :

fix(conversation):#WB-3833 fix abbr for cc or cci

---

conversation/frontend/.gitignore
conversation/frontend/package.json.template
conversation/frontend/scripts/get-tokens/config.json
conversation/frontend/scripts/get-tokens/config.template.json
conversation/frontend/scripts/get-tokens/index.cjs
conversation/frontend/src/components/message-attachments/components/MessageAttachment.tsx

Ajout du script d'Anthony pour recuperer automatiquement les tokens d'un environnement pour s'authentifier en local

buid(conversation)/get-tokens-for-dev

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/features/message-edit/components/RecipientAvatar.tsx
conversation/frontend/src/features/message-edit/components/RecipientListEdit.tsx
conversation/frontend/src/features/message-edit/components/RecipientListItem.tsx
conversation/frontend/src/features/message-edit/components/RecipientListSelectedItem.tsx
conversation/frontend/src/features/message-edit/hooks/useSearchRecipients.tsx
conversation/frontend/src/models/visible.ts

feat(conversation): #WB-3978 broadcast group exception

---

conversation/frontend/src/components/MessageActionDropDown/MessageActionDropDown.tsx
conversation/frontend/src/components/MessageActionDropDown/hooks/useMessageActionDropDown.tsx
conversation/frontend/src/services/queries/message.ts
conversation/frontend/vite.config.ts

feat(conversation): #WB-3637 send message

---

conversation/frontend/src/features/message-edit/components/RecipientListEdit.tsx
conversation/frontend/src/features/message-edit/hooks/useSearchRecipients.tsx
conversation/frontend/src/models/group.ts
conversation/frontend/src/routes/pages/MessageEdit.tsx
conversation/frontend/src/services/api/userService.ts
conversation/frontend/src/services/queries/message.ts
conversation/frontend/src/services/queries/user.ts

Fix issue when adding ShareBookmark. Now it will get all users and groups from this bookmark and add them to the recipients

fix(conversation): #WB-3636 add sharebookmark

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/components/MessageRecipientList/components/MessageRecipientSubList.tsx
conversation/frontend/src/features/message-list/hooks/useToolbarActions.ts
conversation/frontend/src/store/confirmModal.ts

-ajout de la propriété "size" dans la ConfirmModal pour correspondre au design
-fix MessageRecipientSubList warning

fix(conversation):WB-3957 - fix empty trash modal size

---

conversation/frontend/src/components/MessageAttachments/MessageAttachments.tsx
conversation/frontend/src/components/NewMessageButton.tsx
conversation/frontend/src/features/app/Action/AppActionHeader.tsx
conversation/frontend/src/features/message-list/components/MessageListEmpty.tsx

- add route to new message button in empty screen 

fix(conversation)-WB-3833- fixes in message list

---

conversation/frontend/src/features/message-edit/components/RecipientListEdit.tsx
conversation/frontend/src/features/message-edit/hooks/useSearchRecipients.tsx

Force search recipients when typing enter.

fix(conversation): #WB-3636 force search on enter

---

conversation/frontend/src/components/MessageBody.tsx
conversation/frontend/src/features/message-edit/MessageEdit.tsx

fix(conversation): #WB-3437 lost focus position on save draft

---

conversation/frontend/src/services/queries/message.ts

fix(conversation):WB-3988- fix empty screen when have next page

---

.gitignore
conversation/frontend/src/hooks/useMessageAttachments.tsx

display error when add attachment to workspace

fix(conversation):#WB-3971 display error when add attachment to workspace

---

cas/src/main/java/org/entcore/cas/services/OdeRegisteredService.java

Fix fetching of manual functions for ODE CAS response service
https://jira.support-ent.fr/browse/CS-25

feat(ODE): [CS-25] add manual functions to CAS response

---

conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
conversation/frontend/src/services/queries/attachment.ts
conversation/frontend/src/services/queries/folder.ts
conversation/frontend/src/services/queries/message.ts

La date d'un brouillon doit être mise à jour lorsqu’on ajoute ou supprime une pièce jointe.
Côté front, un optimistic update est fait.
Pour ce faire, une fonction utilitaire a été créée et appliquée là où c'était possible.
[WB-4019](https://edifice-community.atlassian.net/browse/WB-4019)
[WB-4019]: https://edifice-community.atlassian.net/browse/WB-4019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

fix(conversation): #WB-4019, update draft date when [at|de]taching files

---

.husky/pre-commit
.husky/pre-push
conversation/frontend/.husky/pre-commit
conversation/frontend/.husky/pre-push
conversation/frontend/package.json.template
conversation/frontend/src/components/FolderActionDropDown.tsx
conversation/frontend/src/components/ProgressBar.css
conversation/frontend/src/features/message-list/components/MessagePreview/MessagePreview.tsx
conversation/frontend/src/features/message/hooks/useMessageNavigation.ts
conversation/frontend/src/features/modals/CreateFolderModal.test.tsx
package.json

Build(conversation)- add husky with pre push script

---

conversation/frontend/package.json.template
conversation/frontend/scripts/get-tokens/index.cjs

build(conversation)- update get-token script

---

conversation/backend/src/main/resources/i18n/fr.json
conversation/frontend/src/features/message-list/components/MessagePreview/MessagePreview.tsx
conversation/frontend/src/features/message/message-header/index.tsx

message preview
- correction date format 
- ajout title date complete
message detail
- correction date format

feat(conversation) WB-4128-format-date message header

---

conversation/frontend/src/components/MessageBody.tsx

fix(conversation): #WB-4160 set focus

---

app-registry/src/main/java/org/entcore/registry/controllers/AppRegistryController.java
broker-parent/broker-api/src/main/java/org/entcore/broker/api/appregistry/AppRegistrationRequestDTO.java
broker-parent/broker-api/src/main/java/org/entcore/broker/api/appregistry/SecuredActionDTO.java
broker-parent/broker-api/src/main/java/org/entcore/broker/api/dto/BaseResponseDTO.java
broker-parent/broker-api/src/main/java/org/entcore/broker/api/utils/BrokerProxyUtils.java
broker-parent/broker/src/main/java/org/entcore/broker/client/NATSBrokerClient.java
session/src/main/java/org/entcore/session/SessionBrokerListenerImpl.java

Cette PR inclut des corrections sur :
- l'enregistrement des apps via broker
- la récupération des droits workflows via broker
Tests d'intégration de la PR liée dans communities

feat(broker,appregistry,session): handle app registry

---

conversation/frontend/src/features/message-edit/components/RecipientListEdit.tsx

affiche un placeholder different au focus du combobox

feat(conversation)-COCO-4139 combobox onfocus onblur

---

conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx
conversation/frontend/src/components/MessageAttachments/MessageAttachments.tsx
conversation/frontend/src/components/MessageBody.tsx
conversation/frontend/src/features/message-edit/MessageEdit.tsx
conversation/frontend/src/hooks/useAdditionalRecipients.ts
conversation/frontend/src/hooks/useMessageAttachments.tsx
conversation/frontend/src/hooks/useMessageIdAndAction.tsx
conversation/frontend/src/hooks/useMessageReplyOrTransfer.tsx
conversation/frontend/src/routes/pages/Message.tsx
conversation/frontend/src/services/api/messageService.ts
conversation/frontend/src/services/queries/attachment.ts
conversation/frontend/src/services/queries/message.ts
conversation/frontend/src/services/utils.ts
conversation/frontend/vite.config.ts

add in reply to param 
fix forward mail with attachments
[#WB-4153](https://edifice-community.atlassian.net/browse/WB-4153)
[#WB-4159](https://edifice-community.atlassian.net/browse/WB-4159)

fix(conversation): #WB-4153 add in reply to param + fix forward mail

---

portal/frontend/vite.config.ts

chore: config vite to build welcome

---

conversation/frontend/src/routes/root/index.css

Cache le bouton "Aide" à l'impression.
https://edifice-community.atlassian.net/browse/COCO-4099

fix(conversation): #COCO-4099, hide help button while printing

---

conversation/frontend/src/features/menu/components/DesktopMenu.css
conversation/frontend/src/features/menu/components/MobileMenu.tsx
conversation/frontend/src/features/message-list/MessageList.tsx
conversation/frontend/src/features/modals/CreateFolderModal.tsx
conversation/frontend/src/routes/root/index.tsx

- scroller dans un message en gardant le reste du site fix
- avoir la toolbar sticky
- corriger le probleme de largeur des dropdown

feat(conversation)-COCO-4122-aside-left-fix

---

portal/frontend/src/components/ApplicationIcon.tsx
portal/frontend/src/routes/root/index.tsx

chore: unset title capitalize

---

portal/frontend/src/components/ApplicationIcon.tsx
portal/frontend/src/layouts/MyAppsLayout.tsx
portal/frontend/src/routes/errors/page-error.tsx
portal/frontend/src/routes/root/index.tsx

fix: common on translate

---

conversation/backend/src/main/java/org/entcore/conversation/controllers/ConversationController.java

Notification display empty subjet 
[COCO-4218](https://edifice-community.atlassian.net/browse/COCO-4218)
[COCO-4218]: https://edifice-community.atlassian.net/browse/COCO-4218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(conversation): #COCO-4218 check empty subjet on notification

---

portal/backend/src/main/resources/i18n/fr.json
portal/frontend/src/components/ApplicationIcon.tsx
portal/frontend/src/features/application-list/ApplicationList.tsx
portal/frontend/src/mocks/mockApplications.json
portal/frontend/src/models/application.ts
portal/frontend/src/services/queries/applications.ts
portal/frontend/src/utils/get-app-name.ts

chore: display name of services app

---

portal/frontend/src/components/ApplicationIcon.tsx
portal/frontend/src/components/ApplicationWrapper.tsx
portal/frontend/src/config/applications-list-enhance.json
portal/frontend/src/features/application-list/ApplicationList.tsx
portal/frontend/src/layouts/MyAppsLayout.tsx
portal/frontend/src/layouts/my-apps.css
portal/frontend/src/mocks/mockApplications.json
portal/frontend/src/models/application.ts
portal/frontend/src/routes/root/index.tsx
portal/frontend/src/services/queries/applications.ts

chore: color app and start enhance file

---

conversation/frontend/src/services/queries/user.ts

Add search user with relatives + children if there is some.
[COCO-4255](https://edifice-community.atlassian.net/browse/COCO-4255)
[COCO-4255]: https://edifice-community.atlassian.net/browse/COCO-4255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: #COCO-4255 user search relatives children

---

portal/frontend/src/components/ApplicationWrapper.tsx

test: useLibraryUrl on recette

---

portal/frontend/package.json.template
portal/frontend/src/components/ApplicationWrapper.tsx
portal/frontend/src/layouts/my-apps.css

fix: accessibility of dropdown

---

conversation/backend/src/main/java/org/entcore/conversation/util/MessageUtil.java

Fix coco 4272 fix null user in from message when deleted user

---

portal/frontend/src/components/ApplicationWrapper.tsx
portal/frontend/src/hooks/useHydrateUserPreferences.ts

fix: hydrate even if preferences null

---

conversation/frontend/src/routes/index.tsx
conversation/frontend/src/routes/pages/Folder.tsx
conversation/frontend/src/routes/redirections/index.tsx

- change url without reload react app for initial redirections
- ne pas charger les messages pour les dossier qui n'existent pas (mauvaise url)

fix(conversation): #COCO-4271 smooth redirections

---

timeline/src/main/java/org/entcore/timeline/services/impl/DefaultTimelineMailerService.java

Migration des requêtes de récupération des notifiations des notifs journalières et hebdomadaires suite à la migration vertx 4
COCO-3980
1. Paramétrer les notifs de l'utilisateur A pour avoir des notifications hebdomadaires sur blog et quotidiennes sur cahier multimédia
2. Avec l'utilisateur B, partager à A un blog et un cahier multimédia
3. Avec un ADMC, appeler les routes /timeline/performWeeklyMailing et /timeline/performDailyMailing
4. Vérifier que les mails de notifs hebdos et quotidiennes arrivent bien

fix(timeline): Fix daily and weekly notifications

---

conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx

All user to reply all when there is a group in cc or to param
[COCO-4296](https://edifice-community.atlassian.net/browse/COCO-4296)
[COCO-4296]: https://edifice-community.atlassian.net/browse/COCO-4296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(conversation): #COCO-4296 can reply all to a group

---

conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx
conversation/frontend/src/components/MessageBody.css
conversation/frontend/src/components/MessageBody.tsx
conversation/frontend/src/components/MessageRecipientList/hooks/useMessageCciToDisplay.tsx
conversation/frontend/src/features/message-list/components/MessagePreview/MessagePreview.test.tsx
conversation/frontend/src/features/message-list/components/MessagePreview/MessagePreview.tsx
conversation/frontend/src/features/message-list/components/MessagePreview/components/SenderAvatar.tsx
conversation/frontend/src/features/message-list/hooks/useToolbarVisibility.ts
conversation/frontend/src/features/message/components/MessageHeader.tsx
conversation/frontend/src/hooks/useInitMessage.tsx
conversation/frontend/src/hooks/useMessageFolderId.tsx
conversation/frontend/src/hooks/useRecall.ts
conversation/frontend/src/hooks/useUserDisplayName.ts
conversation/frontend/src/models/message.ts

A message can have an empty from parameter. Fix issue when there is no from.
[COCO-4291](https://edifice-community.atlassian.net/browse/COCO-4291)
[COCO-4291]: https://edifice-community.atlassian.net/browse/COCO-4291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(conversation): #COCO-4291 allow message from null

---

conversation/frontend/src/features/message-list/components/MessageItem.tsx
conversation/frontend/src/features/message/MessageNavigation.tsx
conversation/frontend/src/features/message/hooks/useMessageNavigation.ts
conversation/frontend/src/routes/pages/Message.tsx
conversation/frontend/src/services/queries/hooks/useToggleUnreadMessageFromQueryCache.ts
conversation/frontend/src/services/queries/message.ts

- mark as read from message navigation
- refacto in hook useToggleUnreadMessagesFromQueryCache
- optimistic update of unread status 
- unread status updated if open from outbox list

fix(conversation):COCO-4213 mark as read from message navigation

---

portal/frontend/src/features/application-list/ApplicationList.tsx

chore: sort search apps

---

Jenkinsfile
broker-parent/broker-client/nest/.gitignore
broker-parent/broker-client/nest/package.json
broker-parent/broker-client/nest/pnpm-lock.yaml
broker-parent/broker-client/nest/src/nats/client.ts
broker-parent/broker-client/nest/src/nats/types.ts
broker-parent/broker-client/quarkus/build.sh
broker-parent/broker-client/quarkus/docker-compose.yml
broker-parent/broker-client/quarkus/pom.xml
broker-parent/broker-client/quarkus/src/main/java/org/entcore/broker/EntNatsServiceClient.java
broker-parent/broker-client/quarkus/src/main/resources/application.properties
broker-parent/broker/pom.xml
build.sh
docker-compose.yml

Inclusion du build des clients dans le pom.xml de entcore. La commande edifice vient de la nouvelle image maven.opendigitaleducation.com/docker/repository/sre-docker-hosted/mvn-java8-node22:1.2.5

fix: build broxer client in maven

---

portal/frontend/src/services/queries/applications.ts

chore: detect extra library app

---

conversation/backend/src/main/java/org/entcore/conversation/controllers/ApiController.java
conversation/backend/src/main/java/org/entcore/conversation/service/ConversationService.java
conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java

[#COCO-3765](https://edifice-community.atlassian.net/browse/COCO-3765)

feat(conversation): #COCO-3765-purge-conversation-messages

---

directory/src/main/java/org/entcore/directory/controllers/StructureController.java

[#COCO-3632](https://edifice-community.atlassian.net/browse/COCO-3632)

fix(directory): #COCO-3632, massmail get sender theme from host

---

conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx
conversation/frontend/src/features/app/Action/AppActionHeader.tsx
conversation/frontend/src/features/menu/hooks/useFolderHandlers.tsx
conversation/frontend/src/features/message-edit/MessageEdit.tsx
conversation/frontend/src/features/message-edit/components/MessageSaveDate.tsx
conversation/frontend/src/features/message-edit/components/RecipientListEdit.tsx
conversation/frontend/src/features/message-edit/hooks/useAutoSaveMessage.tsx
conversation/frontend/src/features/message-list/MessageList.tsx
conversation/frontend/src/features/message-list/components/MessageListHeader.tsx
conversation/frontend/src/features/message-list/hooks/useSelectedMessages.ts
conversation/frontend/src/features/message-list/hooks/useToolbarActions.ts
conversation/frontend/src/features/modals/CreateFolderModal.tsx
conversation/frontend/src/features/modals/MoveMessageToFolderModal.tsx
conversation/frontend/src/features/modals/RenameFolderModal.test.tsx
conversation/frontend/src/features/modals/RenameFolderModal.tsx
conversation/frontend/src/features/modals/TrashFolderModal.tsx
conversation/frontend/src/features/modals/hooks/useFolderActions.ts
conversation/frontend/src/features/modals/hooks/useSignatureHandlers.tsx
conversation/frontend/src/hooks/useInitMessage.tsx
conversation/frontend/src/hooks/useMessageAttachments.tsx
conversation/frontend/src/hooks/useRecall.ts
conversation/frontend/src/hooks/useRights.ts
conversation/frontend/src/routes/pages/Folder.tsx
conversation/frontend/src/routes/root/index.tsx
conversation/frontend/src/services/queries/attachment.ts
conversation/frontend/src/services/queries/folder.ts
conversation/frontend/src/services/queries/message.ts
conversation/frontend/src/services/queries/user.ts
conversation/frontend/src/store/actions.ts
conversation/frontend/src/store/messageStore.ts

Utilisation de zustand vanilla => refacto avec syntaxe plus simple pour react (https://zustand.docs.pmnd.rs/apis/create)
Tutorial pour comprendre : https://www.youtube.com/watch?v=a1k_TgmKQ5M

Refacto coco store zustand

---

common/src/main/java/org/entcore/common/notification/TimelineHelper.java

Rajout de log pour vérifier que le problème d'absence de traduction dans la timeline survennant de manière aléatoire ne vient pas d'une erreur d'accès aux fichiers
[(Enter here Jira or Redmine ticket(s) links)](https://edifice-community.atlassian.net/browse/COCO-2411)
Regarder les logs vérifier la présence des messages de chargement

fix-(timeline): #COCO-2411 add log in i18n timeline loading to track down translation problem

---

conversation/frontend/src/components/MessageActionDropdown/MessageActionDropdown.tsx
conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx

on doit être redirigé sur la liste des messages reçus après envoi
Tciket : https://edifice-community.atlassian.net/browse/COCO-4251?focusedCommentId=94021&sourceType=mention

fix(conversation):COCO-4251 fix redirect avec send message

---

conversation/frontend/src/components/MessageActionDropdown/MessageActionDropdown.tsx
conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx

avoir le loader sur le bouton envoyé au clic
ticket https://edifice-community.atlassian.net/browse/COCO-4253

fix(conversation):#COCO-4253 add spinner when send message

---

admin/src/main/ts/src/app/core/store/models/userdetails.model.ts
admin/src/main/ts/src/app/users/details/sections/connection/user-connection-section.component.html
admin/src/main/ts/src/app/users/details/sections/connection/user-connection-section.component.ts
auth/src/main/java/org/entcore/auth/controllers/AuthController.java
auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java
auth/src/main/java/org/entcore/auth/users/UserAuthAccount.java
directory/src/main/java/org/entcore/directory/controllers/ClassController.java
directory/src/main/java/org/entcore/directory/services/ClassService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultClassService.java
directory/src/main/java/org/entcore/directory/services/impl/DefaultMassMailService.java
directory/src/main/resources/public/template/admin/toaster.html
directory/src/main/resources/public/ts/admin/delegates/actions.ts
directory/src/main/resources/public/ts/admin/delegates/userExport.ts
directory/src/main/resources/public/ts/admin/model.ts
directory/src/main/resources/public/ts/admin/service.ts

branch recréer avec commit de JC sur ce ticket https://edifice-community.atlassian.net/browse/COCO-3778

feat(admin,auth,directory): WB-3778, improved management of federated users

---

auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java

Return user's alias login if exists, else, return login.
[#COCO-4337](https://edifice-community.atlassian.net/browse/COCO-4337)

Fix coco 4337 forgot id user alias or login

---

timeline/src/main/java/org/entcore/timeline/controllers/helper/NotificationHelper.java

fix-(notification): #COCO-4523 add null check on push notif to avoid null pointer

---

conversation/backend/src/main/java/org/entcore/conversation/filters/VisiblesFilter.java

Le filtre de sécurité sur la route send du module conversation utilise la recherche classique de visible pour vérifier les droits sur les to cc et cci du message => utilisation de la méthode optimisée developpée pour les favoris pour vérifier les visibles
https://edifice-community.atlassian.net/browse/COCO-4474

fix-(conversation): #COCO-4474 optimize security filter on send message

---

feeder/src/main/java/org/entcore/feeder/dictionary/structures/Group.java

Les requêtes de constitution des groupes sont assez lentes en production, les différents cas traités en une seule requête font brasser trop de ligne => séparation en deux cas (par groupe ou par positon) pour mieux optimiser les requêtes
https://edifice-community.atlassian.net/browse/COCO-4525

fix-(feeder): #COCO-4525 optimize broadcast linking

---

common/src/main/java/org/entcore/common/s3/S3Client.java
common/src/main/java/org/entcore/common/storage/impl/S3Storage.java

Les videos ne se lancent pas sur IOS due à la gestion des headers range checks du connecteur S3. Ajout des headers et correction d'un bug potentiel sur le client.
(Enter here Jira or Redmine ticket(s) links)](https://edifice-community.atlassian.net/browse/COCO-4527)
* Ajouter des videos dans blog et tenter de les lires sur IOS et android
* Ajouter des fichiers sur blog et tenter de les télécharger

Fix coco 4527 add range check on s3

---

directory/src/main/java/org/entcore/directory/services/impl/filter/NotVisibleFilterPerson.java

Fix missing relatives on my account page.
[#COCO-4529](https://edifice-community.atlassian.net/browse/COCO-4529)

fix(directory): #COCO-4529, fix missing relatives on my account page

---

directory/src/main/java/org/entcore/directory/services/impl/DefaultUserBookService.java

https://edifice-community.atlassian.net/browse/COCO-4596

fix-(directory): #COCO-4596 replace result by an ok + empty result

---

directory/src/main/java/org/entcore/directory/services/impl/DefaultGroupService.java

Ajout d'un type de groupe au retour
[#COCO-4643](https://edifice-community.atlassian.net/browse/COCO-4643)

fix(directory): COCO-4643, liste de diff dans cci uniquement

---

conversation/backend/src/main/java/org/entcore/conversation/service/impl/DeleteOrphan.java

Optimisation de DeleteOrphan.
Traitement avec des LIMIT, en batchs, et renvoi des infos sur le reste à faire (ça peut aider à ajuster les paramètres).
[#COCO-4264](https://edifice-community.atlassian.net/browse/COCO-4264)

fix(conversation): COCO-4264, optimize delete orphans

---

docker-compose.yml

Utiilsation d'une image maven disponible publiquement.

chore: Use a publicly accessible Docker image

---

communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java

Un problème de comparaison d'objet dans l'algorithme de fitlrage des visibles pour les admls lorsqiu'il recherche un parent en recherchant un enfant filtrait ceux-ci. 
https://edifice-community.atlassian.net/browse/COCO-4743

fix COCO-4743 fix adml algorithm to filter relative visible on search visible
