- auth/src/main/java/org/entcore/auth/controllers/SamlController.java
- auth/src/main/java/org/entcore/auth/security/SamlValidator.java
Développements concernant la fédération d'identité pour la mairie de Paris : 
La mairie souhaite que l'URL de retour (utilisée lors de la déconnexion depuis le service provider) soit ajoutée à la réponse SAML (vecteur FrEduUrlRetour).
> [fix FED] : add FrEduUrlRetour vector

- directory/src/main/resources/i18n/fr.json
- infra/src/main/resources/public/js/angular-app.js
- infra/src/main/resources/public/js/lib.js
- infra/src/main/resources/public/template/calendar.html
Module Agenda impossible de consulter les événements créés, ils n’apparaissent plus sur le calendrier.
Autres anomalies :
Contexte : type ressource A : réservation possible plage horaire de 8h à 10h uniquement, type de ressource B : réservation libre
· Clic sur une plage horaire à 11h. Ouverture de création évènement sur le type de ressource A. Le créneau défini est donc de 8h à 10h. Pb : si on change de type de ressource et qu’on met la B, le créneau reste de 8 à 10 alors qu’on a cliqué sur le 11h à la base
· Dans le cas précédent, s’il n’y a pas de ressource sur le type B, alors quand on clique sur le créneau lors de la création, undefined apparait dans le nom de la ressource
· Lors du choix du créneau : Si on met la date du 11/01 8h pour le début de la réservation et le 12/01 10h pour …
> [Fix] display of bookings for calendar module + title horaire

- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/app/core/store/models/group.model.ts
- admin/src/main/ts/app/groups/details/group-details.component.spec.ts
- admin/src/main/ts/app/groups/details/group-details.component.ts
- admin/src/main/ts/app/groups/details/group-internal-communication-rule.resolver.spec.ts
- admin/src/main/ts/app/groups/details/group-internal-communication-rule.resolver.ts
- admin/src/main/ts/app/users/communication/communication-rules.component.spec.ts
- admin/src/main/ts/app/users/communication/communication-rules.component.ts
- admin/src/main/ts/app/users/communication/communication-rules.service.spec.ts
- admin/src/main/ts/app/users/communication/communication-rules.service.ts
- admin/src/main/ts/app/users/communication/communication-test-utils.ts
- admin/src/main/ts/app/users/communication/group-card.component.spec.ts
- admin/src/main/ts/app/users/communication/group-card.component.ts
- admin/src/main/ts/app/users/communication/smart-user-communication.component.ts
- admin/src/main/ts/app/users/communication/user-communication.component.spec.ts
- admin/src/main/ts/app/users/communication/user-communication.component.ts
- admin/src/main/ts/app/users/communication/user-groups.resolver.spec.ts
- admin/src/main/ts/app/users/communication/user-groups.resolver.ts
- admin/src/main/ts/app/users/users.module.ts
- admin/src/main/ts/app/users/users.routing.ts
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- directory/src/main/java/org/entcore/directory/services/UserService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
related to CAV2-379: https://opendigitaleducation.atlassian.net/browse/CAV2-379
This PR:
- adds internal communication rule to the frontend GroupModel model and
restyle code of this file
- expose an backend endpoint to get the user groups and display them on
the frontend
How it works:
- before landing on the communication view the resolvers retrieve the user
and its groups
- smart component loads the groups in the communication rules
service (= store), subscribe to changes in the communication rules store
and make communication rules flow in its children components
- user communication component display the view
- communication rules component display a communication rule table
- group card component display a single group
> [ODE] Show user groups in the communication view

- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/app/users/communication/communication-rules.component.spec.ts
- admin/src/main/ts/app/users/communication/communication-rules.component.ts
- admin/src/main/ts/app/users/communication/communication-rules.service.spec.ts
- admin/src/main/ts/app/users/communication/communication-rules.service.ts
- admin/src/main/ts/app/users/communication/group-card.component.spec.ts
- admin/src/main/ts/app/users/communication/group-card.component.ts
Related to CAV2-381 : https://opendigitaleducation.atlassian.net/browse/CAV2-381
- also fixing a issue when calling the toggle internal communication rule, the service was not emitting a change if the given group was in the receiving column.
> [ODE] highlight related groups in the communication view

- feeder/src/main/java/org/entcore/feeder/csv/CsvFeeder.java
- feeder/src/main/java/org/entcore/feeder/csv/CsvValidator.java
L'import du fichier ONDE parent crée systématiquement un JSONArray alors que le overrideClass est toujours une String
Le problème ne se pose qu'avec paramétrage de la classe (la console d'admin semble faire une pré-validation qui ne provoque pas l'erreur)
Testé en local, semble marcher
> fix(feeder): #23677, Fix ONDE relative import when class is overriden

- admin/src/main/resources/i18n/fr.json
- admin/src/main/resources/public/styles/admin.scss
- admin/src/main/ts/app/core/services/notify.service.ts
- admin/src/main/ts/app/core/store/models/connector.model.ts
- admin/src/main/ts/app/services/connectors/connector/properties/connector-properties.component.ts
- admin/src/main/ts/app/services/connectors/connector/smart-connector.component.spec.ts
- admin/src/main/ts/app/services/connectors/connector/smart-connector.component.ts
- admin/src/main/ts/app/services/services.service.spec.ts
- admin/src/main/ts/app/services/services.service.ts
- admin/src/main/ts/app/services/shared/services-list.component.ts
- admin/src/main/ts/app/shared/ux/components/form-field.component.ts
- admin/src/main/ts/app/shared/ux/components/index.ts
- admin/src/main/ts/app/shared/ux/components/message/message-box.component.ts
- admin/src/main/ts/app/shared/ux/components/message/message-sticker.component.ts
- admin/src/main/ts/app/shared/ux/components/upload-files.component.spec.ts
- admin/src/main/ts/app/shared/ux/components/upload-files.component.ts
- admin/src/main/ts/app/shared/ux/directives/drag-and-drop-files.directive.ts
- admin/src/main/ts/app/shared/ux/directives/index.ts
- admin/src/main/ts/app/shared/ux/services/index.ts
- admin/src/main/ts/app/shared/ux/services/inputFile.service.spec.ts
- admin/src/main/ts/app/shared/ux/services/inputFile.service.ts
- admin/src/main/ts/app/shared/ux/ux.module.ts
feat(adminv2): #CAV2-431, import image for connector icon
Creation of an upload-files component and a drag'n'drop directive to allow user to pick or drag'n'drop files in the connector icon section.
Connector icon can also be a css selector.
> Adminv2: Import image for connector icon

- common/src/main/java/org/entcore/common/http/BaseServer.java
- common/src/main/java/org/entcore/common/http/filter/Trace.java
- common/src/main/java/org/entcore/common/processor/ControllerAnnotationProcessor.java
- common/src/main/java/org/entcore/common/trace/TraceFilter.java
- migration/3.6.0/traces_ttl_index.js
> Pull request liée à celle de [web-utils#5](https://github.com/opendigitaleducation/web-utils/pull/5)
Ajout de l'annotation `@Trace`. Cette annotation permet de tracer les interactions HTTP dans un but "juridique", notamment dans les outils de vie scolaires.
L'utilisation de l'annotation sur une route sauvegarde un objet dans une collection. Par exemple : 
```json
{
"_id" : "a4b2648f-2a89-4ce8-bfc6-05d894cfb66a",
"application" : "Presences",
"user" : {
"login" : "jane.doe",
"id" : "a25cd679-b30b-4701-8c60-231cdc30cdf2"
},
"request" : {
"method" : "POST",
"uri" : "/presences/events",
"params" : {}
},
"entry" : ISODate("2019-05-03T16:15:56.329Z"),
"response" : ISODate("2019-05-03T16:15:56.373Z"),
"action" : "POST_EVENT",
"status" : 201,
"resource" : {
"register_id" : 1019869,
"type_id" : …
```
>  feat(common): #MA-298, Add legal traces

- admin/src/main/ts/app/core/services/routing.service.ts
- admin/src/main/ts/app/groups/groups.resolver.ts
- admin/src/main/ts/app/shared/utils/testing.ts
- admin/src/main/ts/app/users/communication/communication-rules.component.spec.ts
- admin/src/main/ts/app/users/communication/communication-rules.component.ts
- admin/src/main/ts/app/users/communication/group-card.component.spec.ts
- admin/src/main/ts/app/users/communication/group-card.component.ts
- admin/src/main/ts/app/users/communication/smart-user-communication.component.ts
- admin/src/main/ts/app/users/communication/user-communication.component.spec.ts
- admin/src/main/ts/app/users/communication/user-communication.component.ts
Related to CAV2-402: https://opendigitaleducation.atlassian.net/browse/CAV2-402
Sort groups by structure in communication rules view, display structure name in group card and also show buttons in group card based on ADML rights.
> [ODE] sort groups by structure in communication rules view

- cas/src/main/java/org/entcore/cas/services/UuidRegisteredService.java
- cas/src/main/resources/i18n/fr.json
Ajout d'une réponse CAS pour le connecteur Moodle. C'est la même réponse que l'UID mais on y passe l'identifiant de l'utilisateur
> feat(cas): uuid cas response used by Moodle

- admin/src/main/java/org/entcore/admin/Admin.java
- admin/src/main/java/org/entcore/admin/controllers/ZimbraController.java
- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/src/app/core/store/models/group.model.ts
- admin/src/main/ts/src/app/management/management-root/management-root.component.ts
- admin/src/main/ts/src/app/management/management-routing.module.ts
- admin/src/main/ts/src/app/management/management.module.ts
- admin/src/main/ts/src/app/management/zimbra/zimbra-guard.service.ts
- admin/src/main/ts/src/app/management/zimbra/zimbra.component.html
- admin/src/main/ts/src/app/management/zimbra/zimbra.component.scss
- admin/src/main/ts/src/app/management/zimbra/zimbra.component.ts
- admin/src/main/ts/src/app/management/zimbra/zimbra.service.ts
La gestion des droits est bien gérée, concernant la désactivation des routes et de l'onglet "Messagerie", tout fonctionne correctement. Cependant, il ne faudra pas oublier de rajouter la clé de configuration dans ent-core.json. Si cette clé est initialisée à true, l'accès aux routes et à l'onglet "Messagerie" sera possible, mais dans le cas contraire tout sera bloqué.
Clé de configuration à placer dans le composant admin : 
"services" : { 
"zimbra" : true 
}
> Zimbra permission management for admin console V2

- common/src/main/java/org/entcore/common/elasticsearch/ElasticSearch.java
Bonjour,
Nous avons besoin de rajouter une option de config SSL au HHTP Client d'Elastic Search afin qu'il puisse accéder à des elastic search hébergés en HTTPS.
Merci d'avance
> feat(common): Add ssl config in http Client of ElasticSearch

- feeder/src/main/java/org/entcore/feeder/csv/CsvFeeder.java
Objectif: Pouvoir ajouter des fonctions à tous les utilisateurs. Meme si cela est déjà possible, l'ajout d'une fonction sur les utilisateurs non Personnels et Enseignants ne créer pas le groupe de fonction associé.
> fix(feeder): DCN-78 Create functional group on CSV import of students/relatives

- admin/src/main/java/org/entcore/admin/controllers/PlatformInfoController.java
- admin/src/main/ts/src/app/core/resolvers/Config.ts
- admin/src/main/ts/src/app/users/details/sections/administrative/user-administrative-section.component.html
- admin/src/main/ts/src/app/users/details/sections/administrative/user-administrative-section.component.ts
- admin/src/main/ts/src/app/users/details/user-details.component.html
- directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
- directory/src/main/resources/public/js/admin/controller.js
- directory/src/main/resources/public/template/admin-user-details.html
- directory/src/main/resources/public/template/user-edit.html
- directory/src/main/resources/public/template/user-view.html
- directory/src/main/resources/public/ts/controllers/account.ts
- directory/src/main/resources/view-src/mon-compte.html
- infra/src/main/java/org/entcore/infra/Starter.java
Ajout d'une configuration pour désactiver les informations personnelles et ne laisser que les informations nécessaires, à savoir : 
- Adresse
- Code postal
- Ville
- Numéro de téléphone fixe
- Numéro de téléphone portable
Pour activer cette fonctionnalité, il faut ajouter dans le module infra la configuration suivante :
```json
"hidePersonalData": true
```
> feat(personalData/config): #DCN-95 add new configuration

- admin/src/main/resources/i18n/fr.json
- feeder/src/main/java/org/entcore/feeder/csv/CsvReport.java
- feeder/src/main/java/org/entcore/feeder/csv/ProfileColumnsMapper.java
- feeder/src/main/java/org/entcore/feeder/dictionary/users/PersEducNat.java
- feeder/src/main/resources/dictionary/schema/Personnel.json
- feeder/src/main/resources/dictionary/schema/Student.json
- feeder/src/main/resources/dictionary/schema/User.json
Ajout d'un paramètre CSV  `multiEtab` pour chaque utilisateur. Si la valeur est `true` alors : 
- N'écrase plus les données d'établissement après l'import CSV de l'utilisateur sur un autre établissement (un utilisateur importé sur 3 établissements sera lié aux 3 et non pas juste au dernier)
- N'écrase plus les données des fonctions de l'utilisateur liés aux autres établissements
> feat(feeder): DCN-111 Save structure/function of user when importing CSV on another structure

- admin/src/main/ts/src/app/users/details/sections/info/user-info-section.component.html
- admin/src/main/ts/src/app/users/details/sections/info/user-info-section.component.ts
http://support.web-education.net/issues/45896
cadrage fonctionnel : 
Masquer le bouton "Attribuer les droits d'administration" pour les profils élève et parents pour les ADML.
Le bouton doit être visible pour les ADMC.
> [ODE] adminv2 : masquer le bouton d'ajout ADML si le user est un élève ou parent

- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/src/app/services/services.component.ts
- admin/src/main/ts/src/app/services/services.module.ts
- admin/src/main/ts/src/app/services/services.routing.ts
- admin/src/main/ts/src/app/services/widgets/list/widgets-list.component.ts
http://support.web-education.net/issues/46831
Ajout de l'onglet widget au module services, ne contient pas encore l'implémentation de la liste des widgets (dans un ticket à suivre)
> [ODE] adminv2 : ajout de l'onglet widget au module services

- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
Bonjour,
Nous avons besoin de retirer le nom et prénom de l'utilisateur pour les services externes afin de se conformer au RGPD.
Cela se ferait à travers le passage du scope "myInfos-ext".
> fix(directory): Remove personal informations of the user for external services

- directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- directory/src/main/java/org/entcore/directory/services/UserService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
Bonjour, 
Nous avons une requête de la région IDF qui sont embêtés sur le scope myinfos s’appuyant sur la route « directory/myinfos » car nous avons toujours la valeur de functions à null alors que l’utilisateur possède des fonctions.
En analysant le code, il s’agit de la fonction _fullNodeMergeHandler_ qui écrase les fonctions de l’utilisateur. 
Afin de remédier à cela, je modifie le return de la fonction et j'en ai profité pour filtrer les valeurs nulles dans les listes des autres champs afin de ne pas polluer la réponse du scope.
Dans un premier temps, le nouveau RETURN est pris en compte avec un booléen. Ainsi on conserve le comportement actuel et si on constate le problème ailleurs on pourra généraliser le comportement à toutes les autres fonctions. vu avec @nabil-mansouri
Merci …
> fix(myinfos): return the user functions properly

- common/src/main/java/org/entcore/common/http/filter/AppOAuthResourceProvider.java
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- directory/src/main/java/org/entcore/directory/services/UserService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
Bonjour,
Nous avons besoin de créer une oAuth passant certaines informations spécifiques à des services externes afin de se conformer au RGPD.
Voici les informations que ce connecteur oAuth transmettrais :
- userId
- firstName
- lastName
- classId
- level
- uai
- type (élève, parent etc)
- childrenIds (pour les comptes parents)
Cela se ferait à travers le passage du scope "e-tude".
> feat(directory): Add special oAuth e-tude scope

- workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java
- workspace/src/main/resources/public/template/toaster.html
- workspace/src/main/resources/public/ts/controller.ts
- workspace/src/main/resources/public/ts/delegates/scratch.ts
- workspace/src/main/resources/public/ts/directives/fileViewer.ts
- workspace/src/main/resources/view-src/workspace.html
Bonjour,
Nous avons besoin de livrer un correctif pour le connecteur scratch dans l'espace documentaire. 
Cela permettrait de d'abord passer par le nouveau module scratch-connector et de gérer le lien entre l'espace documentaire et l'application Scratch. Ce nouveau module scratch-connecteur apporte une grande couche de sécurité pour les échanges entre la plateforme ENT et l'application Scratch.
Cette version ne présente pas de risque.
Le seul impact sera de modifier la conf du module workspace et mettre :
"enable-scratch" à la place de "scratch-url"
> fix(scratch): fix url when editing scratch project

- common/src/main/java/org/entcore/common/elasticsearch/ElasticSearch.java
Bonjour,
Serait-il possible de rajouter ce petit bout de dev afin que le proxy d'entreprise soit prise en compte pour les développeurs afin qu'il ne soit pas bloqué pour accéder à Elastic search svp ?
> fix(elastic-search): Add proxy options

- auth/src/main/java/org/entcore/auth/security/SamlValidator.java
Suite à la PR https://github.com/opendigitaleducation/entcore/pull/274 et quelques échanges avec @dbreyton :
Cette PR a pour but de sécuriser le String afin d'éviter une NPE dans le cas où null serait mis à la place d'une chaîne vide
> feat(saml): #DRIV-33 add extra security authNRequest to avoid NPE

- auth/src/main/java/org/entcore/auth/security/SamlValidator.java
- auth/src/main/java/org/entcore/auth/services/SamlServiceProvider.java
- auth/src/main/java/org/entcore/auth/services/impl/AbstractSSOProvider.java
- auth/src/main/java/org/entcore/auth/services/impl/SSOCarl.java
- auth/src/main/java/org/entcore/auth/services/impl/SSOGar.java
- auth/src/main/java/org/entcore/auth/services/impl/SSOMatrix.java
- auth/src/main/java/org/entcore/auth/services/impl/SSOPeertube.java
Bonjour,
Nous avons besoin de vérifier que l'utilisateur possède bien le connecteur Riot. Nous avons donc rajouter une condition dans la requête Neo4j du samlMatrix afin de vérifier si c'est le cas sinon il est renvoyé vers la plateforme car il n'a pas les droits.
Cette évolution a un impact sur l'accès au service Riot par SAML (l'utilisateur doit avoir le connecteur qui lui est attribué), mais n'a aucun impact/risque pour les autres connexions SAML.
> feat(access right):Check if the user has the right to go in riot

- build.gradle
- directory/src/test/java/org/entcore/directory/StructureTest.java
- directory/src/test/resources/structures/duplicates.json
- test/src/main/java/org/entcore/test/DirectoryTestHelper.java
Ajout du TU dans le module Directory
Création du jeu de données, le fichier duplicates.json contient les infos : 
- de la structure source avec notamment les roles applicatifs et de widgets, les distributions, les niveaux d'éducation et l'app mobile
- un tableau de structure vers lesquelles dupliquer les settings
- les options de duplication
Suite à l'initialisation des données on appelle la méthode schoolService.duplicateStructureSettings puis on vérifie que dans les structures cibles on a bien les rôles applicatifs et de widget, ainsi que les distributions, les niveaux d'éducation et l'app mobile.
Ajout également de quelques méthodes utilitaires pour les tests dans DirectoryTestHelper.
> [ODE] Ajout du Test Unitaire sur la duplication de settings de structure

- common/src/main/java/org/entcore/common/storage/Storage.java
- common/src/main/java/org/entcore/common/storage/impl/FileStorage.java
- common/src/main/java/org/entcore/common/storage/impl/GridfsStorage.java
- common/src/main/java/org/entcore/common/storage/impl/SwiftStorage.java
Nouvelle fonction ReadStreamFile à partir de la fonction ReadFile pour récupérer un `ReadStream<Buffer>` et non un Buffer
On utilise un webClient et non un HttpRequest dans le module zimbra, en utilisant un sendStream
- cf la PR dans zimbra : https://github.com/OPEN-ENT-NG/zimbra-connector/pull/25
- cf la documentation de WebClient :  https://vertx.io/docs/vertx-web-client/java/
> MZI-29 - create function ReadStreamFile to have a ReadStream<Buffer> when getting document from workspace

- workspace/deployment/workspace/conf.j2
- workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java
- workspace/src/main/resources/public/ts/controller.ts
- workspace/src/main/resources/view-src/workspace.html
Cette feature a pour but de rajouter le sniplet de nextcloud afin de rendre l'arborescence de nextcloud accessible dans l'espace documentaire : 
On injecte le sniplet :
```
<div ng-if="ENABLE_NEXTCLOUD">
<sniplet template="nextcloud-folder/workspace-nextcloud-folder" application="nextcloud"></sniplet>
</div>
```
Celui-ci fera l'affichage (en utilisant le composant `folder-tree`) et adaptera le contenu à droite sur l'affichages des icons/documents
A ajouter dans la configuration de workspace : 
<pre>
{
...
"name": "org.entcore~workspace~...",
"config": {
...
"enable-nextcloud": true,
...
}
...
}
</pre>
>  feat(nextcloud): #DRIV-34 add nextcloud view and config to workspace

- common/src/main/java/org/entcore/common/pdf/NodePdfClient.java
Ajout de `statusMessage()` dans les messages de logs d'erreur pour avoir plus d'information sur les erreurs catché : 
https://github.com/opendigitaleducation/node-pdf-generator/blob/master/controllers/index.js#L25
> refactor(node-pdf): add log status message on error

- common/src/main/java/org/entcore/common/neo4j/Neo4jRest.java
Actuellement quand nous avons une erreur, voici les infos qu'on a : 
`[vert.x-worker-thread-114] 2022-08-01T17:07:17.696+02:00 SEVERE [org.entcore.common.neo4j.Neo4jRest]  Neo4j error in request : /cypher - {"query":"MATCH (s:Structure {id:{structureId}})<-[:BELONGS]-(c:Class)<-[:DEPENDS]-(:ProfileGroup)<-[:IN]-(u:User {id: {studentId}}) RETURN (u.lastName + ' ' + u.firstName) as name, collect(c.name) as className, collect(c.id) as classIds","params":{"structureId":"323f3ebc-0a12-42e1-8ae2-7aabee32a9de","studentId":"c2a01c71-1892-4d05-916e-fa0b70bfe722"}}
`
Nous n'avons pas d'information sur `event` qui est mis en 2eme paramètre dans `logger.error`.
On ajoute `event.getMessage()` dans les messages de logs d'erreur pour avoir plus d'information sur les erreurs du neo4j rest.
> refactor(neo4j-rest): add cause message on error

- communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
Ticket d'origine [redmine 54128](https://support.web-education.net/issues/54128)
Suivi team web [JIRA WB-644](https://opendigitaleducation.atlassian.net/browse/WB-644)
Une liste de diffusion est un groupe de type 'ManualGroup' et de sous-type 'BroadcastGroup', ses membres (nombreux) ne sont pas sensés être visibles même si on peut communiquer vers elle.
Problème : le ticket redmine montre que les membres sont visibles. Confirmé par reproduction locale, voir ticket JIRA.
Le problème de visibilité provient de l'utilisation non-prévue de `DefaultCommunicationService.addLinkWithUsers()` avec la direction NONE, ayant un effet de bord : par défaut, c'est la direction "BOTH" qui se retrouvait appliquée.
Le correctif a consisté à : 
- ne pas appeler cette méthode si le besoin n'est pas là,
- …
> [ODE] communication : les membres d'une liste de diffusion doivent rester non-visibles

- auth/src/main/java/org/entcore/auth/controllers/AuthController.java
Sur les environnement redirigeant vers un site vitrine pour réaliser l'authentification (Nouvelle Aquitaine, ou  Normandie par exemple).
La cinématique SSO "SP provided" de nextcloud (et les autres services dans ce mode) permet de le contexte initial au niveau du site vitrine, ce qui empêche de ramener l'utilisateur sur le service initialement souhaité après l'authentification dans un des  IDP accessibles depuis le site vitrine.
Cette cinématique est notamment utilisée depuis l'application mobile.
La cinématique SAML SSO SP provided permet de résoudre cette problématique par l'usage d'un paramètre plus au moins opaque transmis entre les différents acteurs : RelayState. Ce paramètre transmis sans modification, doit permettre au SP de rediriger l'utilisateur sur la ressource initialement …
> fix(saml): add extra callback redirect when logged in

- portal/src/main/resources/i18n/fr.json
Bonjour,
Comme vu avec @ODE-vpeiro pour plusieurs usage tels que l'import/export via le module Archive nous avons besoin que Formulaire soit dans le i18n du Portal (la clé "form" existe mais pour les usages qui se basent automatiquement sur le nom du module cette clé n'est pas la bonne et aucune correspondance correcte n'est actuellement existante)
Impacts/Risques : 0
> feat(i18n): Add "formulaire" line in Portal i18n

- common/src/main/java/org/entcore/common/storage/Storage.java
- common/src/main/java/org/entcore/common/storage/impl/FileStorage.java
- common/src/main/java/org/entcore/common/storage/impl/GridfsStorage.java
- common/src/main/java/org/entcore/common/storage/impl/SwiftStorage.java
Cette Pull Request permet de répondre au besoin du ticket Zimbra MZI-88/90 qui consiste à stocker un fichier directement dans l'espace documentaire en plus de pouvoir le télécharger sur son ordinateur.
On implémente une méthode qui reprend l'instruction de `writeBuffer` (création folder/fichier avec un id retourné …) pour faire du [write ](https://vertx.io/docs/apidocs/io/vertx/core/streams/WriteStream.html)[stream](https://vertx.io/docs/apidocs/io/vertx/core/streams/Pipe.html).
Exemple d'implémentation :  https://github.com/OPEN-ENT-NG/zimbra-connector/pull/32
> feat(buffer-stream): #MZI-90 add write buffer methods in stream asynchronous

- directory/src/main/resources/public/ts/admin/delegates/userInfos.ts
Il est possible de modifier les informations sur le compte ADML car le champs est toujours modifiable en passant d’une fiche à l’autre
À chaque changement d'utilisateur (dans la méthode `selectUser` donc), on :
- réinitialise toutes les données contenant les modifications potentielles effectuées par l'utilisateur sur l'utilisateur précédent
- on repasse à `false` tous les booléens indiquant que l'on est en cours d'édition
Le back n'a pas été modifié car certaines fonctionnalités de la console d'admin sont présentées en cohérence avec le comportement actuel du back.
Avec un utilisateur ayant accès au paramétrage de la classe j'ai :
- ouvert la fiche dudit utilisateur
- cliquer sur "modifier" au niveau du nom d'affichage
- cliquer sur "suivant" (affichage d'un ADML)
- constater que le champ …
> fix(directory): #WB-1501, leave edition mode while browing users in class settings app

- gradle.properties
The upgrade to 3.9.14 seems to come with some regressions in form handling and other features not fully identified that prevent the ENT from operating correctly so the upgrade has been postponed
> #WB-1652, rollback vertx upgrade (3.9.14 -> 3.9.5)

- .github/PULL_REQUEST_TEMPLATE/external_contribution.md
- .github/PULL_REQUEST_TEMPLATE/internal_contribution.md
- .github/pull_request_template.md
Voici une proposition de 2 templates de pull requests pour le projet entcore (aisément transposable aux autres modules).
Elle reprend pour partie le template déjà établie par Clément pour le front avec des spécifités liées au back.
Je fais la PR sur master car il faut que les templates soient sur la branche par défaut (master) pour être pris en compte.
> chore(doc): pull requests templates

- common/src/main/java/org/entcore/common/http/filter/AppOAuthResourceProvider.java
- common/src/main/java/org/entcore/common/http/response/DefaultResponseHandler.java
- session/src/main/java/org/entcore/session/AuthManager.java
Il était impossible de valider le 2FA par Postman.
Ce problème était dû au fait que la recréation de la session positionnait un cookie oneSessionId, indépendamment du mode d'authentification de l'utilisateur, ce qui entraînait une confusion au niveau des filtres et l'attribut de requête client_id n'était plus positionné, forçant ainsi la vérification du token xsrf qui plante systématiquement dans le cas d'une requête OAuth.
La correction consiste en 2 points :
1. Dans AuthManager.recreateSession on ne renvoie plus le sessionId si la session n'a pas changé d'identifiant
2. Dans DefaultResponseHandler.recreateSessionHandler on ne positionne pas le cookie si on est en OAuth
WB-1670
Les tests du ticket
- …
> [ODE] fix(session): #WB-1670, do not set oneSessionId cookie for oauth authenticated users

- build.gradle
- common/src/main/java/org/entcore/common/http/request/JsonHttpServerRequest.java
- common/src/main/java/org/entcore/common/http/response/DefaultResponseHandler.java
- common/src/main/java/org/entcore/common/session/SessionRecreationRequest.java
- common/src/main/java/org/entcore/common/user/UserUtils.java
- common/src/test/java/org/entcore/common/user/UserUtilsTest.java
- session/src/main/java/org/entcore/session/AuthManager.java
- session/src/main/java/org/entcore/session/MapSessionStore.java
- session/src/main/java/org/entcore/session/SessionStore.java
- test/src/main/java/org/entcore/test/HttpTestHelper.java
Lorsque le temps de vie des tickets OAuth est supérieur à ceux des sessions Redis, une session Redis périmée ne peut être recrée (erreur :`Session not found. 4`).
Désormais, lorsque l'on tente de récupérer une session pour un utilisateur authentifié via oauth on va tenter de recréer la session si celle-ci n'existe plus dans les stores
WB-1659
1. Avoir ça dans le springboard (session redis avec 1 minute de temps de vie de session)
```
{
"name": "com.opendigitaleducation~session-redis~1.3-SNAPSHOT",
"config": {
"listen-expired-session": false,
"session_timeout": 60000,
"redis-pool-size": 50,
"redisConfig": {
"host": "localhost",
"port": 6379
}
}
},
```
2. Authentifier catherine.bailly en mode mobile
3. …
> [ODE] recreate a session for an oauth-authenticated user

- common/src/main/java/org/entcore/common/http/filter/MandatoryUserValidationFilter.java
- common/src/main/java/org/entcore/common/user/UserUtils.java
- session/src/main/java/org/entcore/session/AuthManager.java
For some scenarios (like OAuth client credentials authentication), the user for whom we want to create a session does not exist. In such cases, a call to createSession should not fail but return null like before.
WB-1667
Tymeline Integration test 
> [ODE] do not fail to create session if the user does not exist in Neo4J

- common/src/main/java/org/entcore/common/http/filter/MandatoryUserValidationFilter.java
- common/src/main/java/org/entcore/common/http/response/DefaultResponseHandler.java
- common/src/main/java/org/entcore/common/user/UserUtils.java
Lorsque, connecté en mode oauth client_credentials, on tente de publier sur la timeline, on récupère une erreur 500 au lieu d'un OK 201.
L'erreur rencontrée est la suivante :
`java.lang.IllegalStateException: Request has already been read`
Elle était due à une mauvaise gestion des pause/resume dans le filtre  du MFA ainsi que lors de la recréation de la session.
WB-1667
Integration tests
> [ODE] do not read http body multiple times

- common/src/main/java/org/entcore/common/explorer/ExplorerMessage.java
Adding TrashedBy Field Explorer Message to be handled in EUR ingestion process. To be later stored in Elastic Database.
https://opendigitaleducation.atlassian.net/browse/WB2-616
Local manual dev test :
1. Creating a resource and share it to reader users
2. Updating the resource by manager
3. Checking that reader users received a notification on update of the shared resource
4. Trashing the resource by a reader user
5. Updating the resource by a manager
6. Checking that reader users didn't receive notification on update of the trashed (then muted) shared resource
- Unit tests were added and/or …
> Feat trashed by

- auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
- common/src/main/java/org/entcore/common/datavalidation/impl/AbstractDataValidationService.java
- common/src/main/java/org/entcore/common/datavalidation/impl/DefaultUserValidationService.java
- common/src/main/java/org/entcore/common/datavalidation/utils/UserValidationFactory.java
- infra/deployment/infra/conf.j2
Les codes de validation des données ou de MFA ne devraient pas être stockés en clair dans la base de données, même s'ils sont temporaires.
L'implémentation proposée ici consiste à supporter un nouveau paramètre (clé de cryptage) et à l'utiliser lors de l'écriture / lecture d'un code en BDD.
WB-1700
Validation d'un numéro mobile + MFA, en vérifiant manuellement les codes reçus pas SMS et leurs cryptages dans Neo4j.
> [ODE] WB-1700 cipher codes for sms/email validation, and MFA, in DB

- infra/src/main/java/org/entcore/infra/controllers/MonitoringController.java
- infra/src/main/resources/jsonschema/cspReport.json
On doit générer un log à partir des rapports de violation de règle CSP, contenant la source non-souhaitable de l'iframe et l'URL de l'application qui l'a affichée.
Ces logs permettront de monitoring les contenus tiers embarqués dans les contenus riches.
WB-744
1. testé sur un ENT local à partir d'un rapport généré via Postman
2. pas de conf nginx en local...
> [ODE] Log CSP violation reports

- Jenkinsfile
- auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
- common/src/main/java/org/entcore/common/datavalidation/utils/UserValidationFactory.java
- infra/deployment/infra/conf.j2
Le paramétrage par défaut empêche le tests unitaires de passer sur certaines applis (dont CRM)
Ce commit vient corriger ce soucis.
WB-1772
Ai pu exécuter les TUs du CRM.
> [ODE] Fix unit tests

- cas/src/main/java/org/entcore/cas/services/ElmsRegisteredService.java
Change attributes for ElmsRegisteredService :
- modified tag "fonction" for "profil" to display SDET profil "National_X".
- create tag"inValidateurGroups" return true or false if the user is in manual groupe "Valideur de commande" or not.
Change "isInGroup" future, to avoid error if it can't retreive gar-connector ressources. Now complete promise with empty JsonObject and return "false".
You need to have or create a manual group "Valideur de commande", add someone to this group.
In the response you'll have …
> fix(elmsRegistered): #COE-3 change attributes for eLMS CAS authentication

- cas/src/main/java/org/entcore/cas/services/EduMediaRegisteredService.java
Added missing case for EduMediaRegisteredService CAS authentication. The case for user (a relative one) is now managed.
You need to have a relative user :
In the response you'll have <cas:ENTPersonProfils>National_2<cas:ENTPersonProfils>
> fix(eduMediaCas): #COE-16 add missing case when user is a relative

- auth/src/main/java/org/entcore/auth/services/impl/SSOJira.java
Added attribute to SSOJira authentication :
- if the user is a "Teacher" or "Personnel", "jira-personnel-ent" group will be added to the response.
- if the user is an "ADML", "jira-administrateur-ent" group will be added to the response.
You need to test the response with a "Teacher" user, a "Personnel" user and an "ADML" user
- If the user is a "Teacher" or "Personnel" you will see <cas:jira-personnel-ent></cas:jira-personnel-ent>
- If the user is an "ADML" you will see …
> feat(SSOJira): #COE-6 add attributes for specifics groups

- cas/src/main/java/org/entcore/cas/services/ElmsRegisteredService.java
- cas/src/main/resources/i18n/en.json
- cas/src/main/resources/i18n/fr.json
Adaptations needed for version 2.0 of the CAS:
- add login to tags
- rename eLMS to eMLS
- change tag inValidateurGroup to inValidateurGroups
https://support.web-education.net/issues/62131
On the admin console:
1. create an eMLS connector for a structure
2. assign it to a group where there is an user account you can connect with
On Postman:
1. log into the platform with the previoulsly noted user account (expected response: 302)
2. call ```/cas/login?service=[your_connector_url]&gateway=true``` (expected response: 302)
3. call ```/cas/serviceValidate?service=[your_connector_url]&[your_apptoken]``` 
expected response: 200 with body
body example :
```
<cas:serviceResponse …
```
> fix(register): #COE-3 add login to response

- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/src/app/admc/search/admc-search.module.ts
- admin/src/main/ts/src/app/admc/search/admc-search.service.ts
- admin/src/main/ts/src/app/admc/search/components/user-search-input/user-search-input.component.html
- admin/src/main/ts/src/app/admc/search/components/user-search-input/user-search-input.component.scss
- admin/src/main/ts/src/app/admc/search/components/user-search-input/user-search-input.component.ts
- admin/src/main/ts/src/app/admc/search/components/user-search-list/user-search-list.component.html
- admin/src/main/ts/src/app/admc/search/components/user-search-list/user-search-list.component.scss
- admin/src/main/ts/src/app/admc/search/components/user-search-list/user-search-list.component.ts
- admin/src/main/ts/src/app/admc/search/transverse/admc-search-transverse.component.html
- admin/src/main/ts/src/app/admc/search/transverse/admc-search-transverse.component.ts
- admin/src/main/ts/src/app/core/enum/SearchTypeEnum.ts
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- directory/src/main/java/org/entcore/directory/pojo/TransversalSearchQuery.java
- directory/src/main/java/org/entcore/directory/pojo/TransversalSearchType.java
- directory/src/main/java/org/entcore/directory/services/UserService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
Modification de la requête Cypher utilisée pour réaliser la recherche transverse afin d'en diminuer le temps d'exécution.
Cette requête était longue principalement à cause du filtre `...WHERE AND u.displayNameSearchField CONTAINS {searchTerm}...` car la clause `CONTAINS` ne peut s'appuyer sur aucun index. Nous avons donc scinder le champ de recherche en 2 champs `firstName` et `lastName` qui vont chercher dans les champs `firstNameSearchField` et `lastNameSearchField` à l'aide d'un `STARTS WITH` qui lui peut s'appuyer sur les indexes.
**NB :**  Le fait de passer d'une recherche avec `contains` à une recherche avec `starts with` entraîne une régression fonctionnelle mais celle-ci est assumée.
WB-1368 …
> [ODE] Diminuer le temps de la recherche transverse d'utilisateurs

- admin/src/main/ts/src/app/admc/search/unlinked/details/user-details.component.html
- admin/src/main/ts/src/app/admc/search/unlinked/details/user-details.component.ts
- admin/src/main/ts/src/app/admc/search/unlinked/unlinked.service.ts
- admin/src/main/ts/src/app/users/users.service.ts
Dans la console admin, sur la page ADMC "personnes non-rattachées", indiquer pour les comptes qui sont en fusion, avec quel compte ils sont fusionnés (avec un lien direct vers la fiche profil)
WB-1769
Développement front (adminv2)
1. Fusion par clé de 2 comptes parents
2. Accès à l'écran Personnes non-rattachées
3. Ouverture du compte fusionné
4. Test de la feature
> [ODE] Pouvoir défusionner un compte depuis le menu personnes "non-rattachées"

- admin/src/main/resources/i18n/fr.json
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
- feeder/src/main/java/org/entcore/feeder/dictionary/structures/DuplicateUsers.java
- feeder/src/main/java/org/entcore/feeder/dictionary/structures/User.java
This PR implements the following behavior :
- creating a backup node on a user when merged to another, that stores relation data about communication, groups dependencies...
- restoring user relations from the backup node when the user is detached from the user he merged with.
https://opendigitaleducation.atlassian.net/browse/WB-1767
Manual dev tests with AAF profiles
> Feat wb 1767 backup and merge

- feeder/src/main/java/org/entcore/feeder/ManualFeeder.java
- feeder/src/test/java/org/entcore/feeder/test/integration/java/FeederTest.java
Fix : when manually adding a user to a **class profile group**, it doesn't create a relation to the **structure profile group** if it already exists. If the relation to the structure profile group didn't exist before, it is created and marked as `MANUAL`.
The associated test covers :
- the creation of the relation between user and class profile group
- the non-creation of the relation between user and structure profile group, because already existing.
https://opendigitaleducation.atlassian.net/browse/WB-1635
- Semi-unit tests with an embedded neo4j database.
- Manual dev tests 
- I …
> fix-WB-1635 add user to class with unique relation to structure

- common/src/main/java/org/entcore/common/explorer/IExplorerFolderTree.java
- common/src/main/java/org/entcore/common/explorer/IExplorerPluginClient.java
- common/src/main/java/org/entcore/common/explorer/IExplorerSubResource.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerFolderTree.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerFolderTreeMongo.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerFolderTreeSql.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPlugin.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginClient.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginResourceMongo.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginResourceSql.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerRepositoryEvents.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResource.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResourceMongo.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResourceSql.java
- common/src/main/java/org/entcore/common/explorer/to/ExplorerReindexResourcesRequest.java
- common/src/main/java/org/entcore/common/explorer/to/ExplorerReindexResourcesResponse.java
- common/src/main/java/org/entcore/common/explorer/to/ExplorerReindexSubResourcesRequest.java
- common/src/main/java/org/entcore/common/service/impl/MongoDbRepositoryEvents.java
- common/src/test/java/org/entcore/common/explorer/ExplorerRepositoryEventsTest.java
- gradle.properties
Permettre aux apps branchées à l'EUR d'automatiquement réindexer les ressources importées via `ExplorerRepositoryEvents`.
- remplacements de toutes les fonctions `getForIndexation` par une unique fonction `reindex`
- regroupement des critères de réindexation dans un unique objet `ExplorerReindexResourcesRequest` (et suppression au passage des `Optional` en tant que types de champs de classe ou d'arguments de méthodes pour respecter l'esprit des [Optional](https://blog.joda.org/2014/11/optional-in-java-se-8.html)
- Ajout aux routes de réindexation la possibilité de réindexer par (ids)
- Mise à jour de la version de `web-utils`
Lié à
- https://github.com/opendigitaleducation/web-utils/pull/17
- https://github.com/opendigitaleducation/explorer/pull/13
WB2-959
Please check the name of the …
> [ODE] Indexer les ressources importées depuis workspace

- common/src/main/java/org/entcore/common/explorer/ExplorerMessage.java
Lors de la modification des propriétés d'une resource, les droits de partages sont vidés parce que la valeur par défaut des droits est un tableau vide, qui est interprété par l'EUR comme le fait de vider les droits de partages. La valeur par défaut `[]` a donc été remplacé par un `null` qui a l'effet escompté (ne rien faire sur les partages quand on n'a pas d'informations à leur sujet).
WB2-996
Le test du ticket
> [ODE] Ne pas réécrire les droits de partages après la modification des propriétés d'une ressource

- feeder/src/main/java/org/entcore/feeder/dictionary/structures/User.java
- feeder/src/test/java/org/entcore/feeder/test/integration/java/FeederTest.java
- tests/src/main/scala/org/entcore/test/scenarios/DirectoryScenario.scala
Optimisations des requêtes d'ajout et de retrait de droits ADML sur des structures chapeau.
L'optimisation consiste principalement à retirer les `collect` & `unwind`, inutiles et très coûteux.
Dans le cas de la méthode d'ajout de droits ADML, on ne considère plus le concept de Function**s** ni le fait de donner des droits d'admin sur une classe, car la méthode n'est pas appelée en pratique pour ces cas, à part dans des scénarios de tests  : https://github.com/opendigitaleducation/entcore/blob/70d01721b615765eaa4062ddf1083ee5d663e94a/tests/src/main/scala/org/entcore/test/scenarios/DirectoryScenario.scala#L168C14-L168C14
Des test "unitaires" ont également été ajoutés pour couvrir ces deux cas fonctioneles 
https://edifice-community.atlassian.net/browse/WB-1877
Please check options that are …
> Optimization on adding and removing local admin rights

- build.gradle
- infra/src/main/java/org/entcore/infra/controllers/MonitoringController.java
Le but de cette PR est de mettre à disposition des différents verticles de l'ENT une map décrivant plus précisément les informations d'une module déployé. Ces informations sont pour l'instant :
le dernier commit du code déployé
la branche du module
l'horodatage du build
Ces informations sont lues depuis le fichier MANIFEST.MF du module déployé.
Ajout d'une nouvelle route ` /monitoring/detailedVersions` pour récupérer les metadata du manifest.mf.
WB-1923
> [EDIFICE] Add scm information to manifest files

- directory/src/main/java/org/entcore/directory/security/UserbookCsrfFilter.java
- directory/src/test/java/org/entcore/directory/UserbookCsrfFilterTest.java
Les appels à Userbook sont filtrés (entre autre) par UserbookCsrfFilter qui impose une vérification pour le mobile (à l'inverser de CsrfFilter dont il dérive).
Cette PR vise à reporter dans UserbookCsrfFilter le test fait dans CsrfFilter afin de laisser passer les appels du mobile.
WB-2046
- unit tests
- test dans postman de l'appel à `{{URL}}/userbook/api/edit-user-info-visibility?info=health&state=public` en étant authentifié mobile
> [EDIFICE] Désactivation de la vérification CSRF pour les appels mobile

- feeder/src/main/java/org/entcore/feeder/dictionary/structures/User.java
- infra/deployment/infra/conf.j2
- infra/src/main/java/org/entcore/infra/Starter.java
Récupération de la configuration des métriques (si elle existe) dans le module infra pour la mettre dans la configuration partagée.
WB-2009
1. Démarrer le serveur sans la configuration
2. Constater qu'un warning est écrit dans les logs
3. Démarrer le serveur avec la configuration 
4. Créer un blog
5. Créer une publication
6. La publication contient bien en base un champ contentJson non null et correspondant au contenu
> [Edifice] Récupération de la configuration des métriques

- admin/src/main/ts/src/assets/admin.scss
This completes the first fix for the WB-2077 ticket.
An &lt;ode-list&gt; component had been specialized by a new &lt;admc-user-search-list&gt; component during WB-1368, but CSS was missing. Corrected here.
WB-2077
Used `./build.sh ngWatch` to reproduce and correct the UI.
> [EDIFICE] fix(admin v2): #WB-2077, transversal search CSS

- admin/src/main/ts/src/app/groups/details/manage-users/input/group-input-users/group-input-users.component.ts
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
This commit fixes the ADML transversal search of a user (in groups management), that was taking too much time by not applying the _searchTerm_ correctly.
WB-2089
* `./build.sh ngWatch`
* connect to localhost and reproduce the problem
* fix it
* ensure the correction works as expected, without any error message
* `./build.sh test`
* => 100% successful
> fix(admin): #WB-2089, fix ADML transversal search which was too long

- feeder/src/main/java/org/entcore/feeder/dictionary/structures/DuplicateUsers.java
- feeder/src/test/java/org/entcore/feeder/dictionary/structures/DuplicateUsersTest.java
- feeder/src/test/java/org/entcore/feeder/dictionary/structures/MergeUsersINETest.java
Après la fusion de comptes par INE, si l'utilisateur restant après la fusion n'avait pas d'`Userbook` avant la migration alors on le rattache au userbook de l'ancien utilisateur.
Cependant, on ne changeait pas le champ `userid` de ce `Userbook`, ce qui crée des problèmes sur d'autres processus (authentification, quotas, etc.).
Le but de cette PR est de corriger ce mécanisme en spécifiant la valeur du champ `userid`.
WB-2115
Nouveaux tests unitaires
> [EDIFICE] Correction création de doublons de UserBook

- common/src/main/java/org/entcore/common/service/impl/BasicQuotaService.java
- common/src/test/java/org/entcore/common/service/impl/BasicQuotaServiceTest.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserBookService.java
- directory/src/test/java/org/entcore/directory/org/entcore/directory/services/impl/DefaultUserBookServiceTest.java
- feeder/src/main/java/org/entcore/feeder/dictionary/structures/DuplicateUsers.java
Dans certaines circonstances (suite à une fusion par INE par exemple) il se peut qu'un noeud User se retrouve connecté à un nœud UserBook dont le champ userid ne reflète pas l'id de l'utilisateur cible.
Le but de cette PR est de palier ce genre d'incohérence de la base de données en remplaçant les occurrences de `MERGE (m:UserBook { userid : {userId}})` par des `MERGE (u:User{id:{userId}})-[:USERBOOK]->(m:UserBook)`
HDF-1267
Les 2 nouvelles classes de TU introduites par cette PR.
> [EDIFICE] Empêcher la création de doublon de noeud UserBook

- build.gradle
- common/src/main/java/org/entcore/common/utils/HtmlUtils.java
- common/src/main/java/org/entcore/common/utils/SanitizerUtils.java
- common/src/test/java/org/entcore/common/utils/HtmlUtilsTest.java
- common/src/test/java/org/entcore/common/utils/SanitizerUtilsTest.java
- gradle.properties
Le but de cette PR est de sanitize des champs HTML de tout type d'injections xxss (base64, text, href, src, event, hexa, html caracter...)
J'ai listé tout les attributs et éléments html autorisés dans le html envoyé (source mozilla)
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
https://developer.mozilla.org/en-US/docs/Web/HTML/Elements
- [X ] Bug fix (PATCH)
- [ x] common
Des tests unitaires permettent de vérifier:
- que les attributs style et classe sont conservés
- les élements de base sont conservés
- les url relative/absolu href sont conservé
- les src attributs sont conservés
- les élements de tables sont conservés
- les élements mathjax sont conservés
- les balises scripts sont …
> [EDIFICE] #Wb2-995 XSS Sanitizer

- directory/src/main/resources/jsonschema/updateUser.json
Supporter la valeur `nulle` pour les champs de la route `[PUT]/directory/users/u:userId`
WB-2154
Le test du ticket
> [EDIFICE] authorize null values for updated users' fields

- directory/src/main/resources/public/ts/controllers/directory.ts
- gradle.properties
Add a filter onto the user info page to hide data that is private, even if the current user is an ADML/ADMC.
- https://edifice-community.atlassian.net/browse/MOZO-77
1. Configure a non-admin account to hide some private info (mobile phone, email, etc)
2. Log in with an admin account and go to the non-admin user page. Private info mustn't show.
3. Go into the admin to see the non-admin user page. Private info must show.
> fix(directory): MOZO-77 hide private info from user info page

- common/src/main/java/org/entcore/common/explorer/ExplorerMessage.java
Enrichissement de la méthode de création générique de sous-ressource avec la **version**.
Nécessaire pour implémenter : https://edifice-community.atlassian.net/browse/WB-2008
- Tests dev manuels : création et mise à jour de billets de blog, vérification de l'existence des champs content & version dans la base elastic
- Mise à jour des tests unitaires côté Explorer : https://github.com/opendigitaleducation/explorer/pull/27
> WB-2008 providing plain text content to explorer for indexation

- common/src/main/java/org/entcore/common/explorer/ExplorerMessage.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerSubResource.java
Implémentation par défaut pour la gestion des sous-ressources.
https://edifice-community.atlassian.net/browse/WB-2008
Unit tests and manual dev tests
> Wb 2008 explorer subresource content handles version

- common/src/main/java/org/entcore/common/folders/impl/InheritShareComputer.java
- common/src/main/java/org/entcore/common/folders/impl/QueryHelper.java
- workspace/src/test/java/org/entcore/workspace/FolderTest.java
- workspace/src/test/java/org/entcore/workspace/ShareComputerTest.java
Ce fix corrige le cas suivant:
- je crée un dossier A1 et un sous dossier A2
- je supprime A1
- je restaure A2
- A2 devient un dossier racine il conserve ses partages hérités
Le problème c'est que si A2 est un dossier racine il ne peut pas hérités de partage (puisqu'il n'a plus de parent) alors ses partages hérités deviennent des partages direct.
L'objectif du fix est de corriger ce cas suivant en settant shared=inheritedShared
WB2-741
- [ X] Bug fix (PATCH)
- [X ] common
- [X ] workspace
J'ai ajouté un test dans FolderTest qui simule le scénario précèdent en s'assurant que le dossier A2 (devenu racine) a bien des partages directs une fois restauré …
> [EDIFICE] set shared when restoring subfolder

- common/src/main/java/org/entcore/common/postgres/PostgresClientPool.java
- common/src/test/java/org/entcore/common/postgres/PostgresClientPoolTest.java
L'implémentation de RowStream renvoyée par PostgresClientPool posait 2 problèmes :
- les appels aux fonctions permettant de positionner les handlers fermaient la transaction courante, entraînant entre autres, l'échec de la récupération des éléments à indexer dès lors qu'il y en avait plus que `batchSize`
- les appels aux fonctions _fluent_ retournaient l'objet proxyfié et non le proxy, empêchant donc silencieusement  l'appel aux fonctions surchargées.
[#WB-2265](https://edifice-community.atlassian.net/browse/WB-2265)
1. Se connecter à la base pg
2. Supprimer l'état d'ingestion de tous les sujets à l'aide de la commande suivante 
```sql
update exercizer.subject SET  ingest_job_state = '';
```
3. Se …
> [EDIFICE] [Explorer] Correction de la gestion des streams Postgres

- workspace/src/main/resources/public/ts/delegates/lool.ts
- workspace/src/main/resources/view-src/workspace.html
Move LOOL action (create document) from under the folder tree to the title bar with the import button
[WB-2247](https://edifice-community.atlassian.net/browse/WB-2247)
1. Go to workspace app and check the place of the button "Create document"
[WB-2247]: https://edifice-community.atlassian.net/browse/WB-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat: #WB-2247 Move LOOL aciton in Workspace to the title bar

- workspace/src/main/resources/public/ts/delegates/lool.ts
- workspace/src/main/resources/view-src/workspace.html
Move LOOL action (create document) from under the folder tree to the title bar with the import button
Related to [PR ](https://github.com/opendigitaleducation/entcore/pull/402) which was Merge in 4.12.1
[WB-2247](https://edifice-community.atlassian.net/browse/WB-2247)
1. Go to workspace app and check the place of the button "Create document"
[WB-2247]: https://edifice-community.atlassian.net/browse/WB-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat wb 2247 move lool action

- build.gradle
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPlugin.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginResourceMongo.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginResourceSql.java
- common/src/main/java/org/entcore/common/explorer/to/ExplorerReindexResourcesRequest.java
- gradle.properties
Permettre de réindexer les ressources par leur état d'ingestion.
wb-2243
1. Create a blog
2. In mongo, set the `ingest_job_state` to KO and modify the field `description`
3. With an ADMC, go to http://localhost:8090/explorer/reindex/blog/blog?states=KO
4. Verify that the return of the call says that one message was concerned
5. Verify in mongo that `ingest_job_state` is set to OK
6. Verify in opensearch that the corresponding document has a `description` matching the one in the database
> [EDIFICE] Réindexation des ressources par leur état d'ingestion

- feeder/src/main/java/org/entcore/feeder/csv/CsvValidator.java
- feeder/src/main/resources/i18n/fr.json
Update feeder module to change the error translation when importing CSV with duplicate lines
[JIRA Ticket](https://edifice-community.atlassian.net/browse/WB-1829)
1. Go to the admin console
2. Go to the import/export page ( `imports-exports/import-csv` )
3. Import a CSV with a duplicate line
4. on the step 4 you will see an error message this message will be updated according to the JIRA Ticket spec
> Fix: #WB-1829 Update error duplicate line in CSV translation

- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPlugin.java
- common/src/main/java/org/entcore/common/service/impl/MongoDbRepositoryEvents.java
Lors de la suppression du propriétaire la ressource associée n'était pas supprimé de l'EUR.
Ce fix vient corriger celà en notifiant l'EUR d'une suppression lorsque la ressource Mongo est supprimé de la BDD
Au passage, j'ai ajouté dans la méthode "reindex" des notifications de Delete si l'EUR demande à réindexer une ressource qui n'existe plus dans la BDD primaire
#WB2-1273
- [ X] Bug fix (PATCH)
- [X ] common
Des tests ont été fait sur mindmap pour tester le RepositoryEventMongo associé à l'EUR:
- import d'un fichier => doit créer la ressource dans OpenSearch
- suppression d'un utilisateur en partage => doit mettre à jour les partages dans l'EUR
- suppression d'un groupe en partage => doit mettre à …
> [EDIFICE] #WB2-1273, Synchronisation de OpenSearch lors de la suppression d'un utilisateur

- common/src/main/java/org/entcore/common/http/response/DefaultResponseHandler.java
Ajout d'une fonction utilitaire permettant de récupérer un handler renvoyant :
- un code de succès particulier ainsi que le résultat jsonifié si le traitement en amont à réussi
- un code d'erreur si le traitement en amont a échoué
[WB-2294](https://edifice-community.atlassian.net/browse/WB-2294)
[WB-2294]: https://edifice-community.atlassian.net/browse/WB-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [EDIFICE] Ajout de fonction utilitaire

- auth/src/main/java/org/entcore/auth/controllers/AuthController.java
Provides Mobile team an API endpoint to verify that a reset code matches with the login or the alias login.
https://edifice-community.atlassian.net/browse/WB-1588
Manual dev tests of the API on local environment.
Additionally, both `userAuthAccount.matchResetCode` and `userAuthAccount.matchResetCodeByLoginAlias` methods called in the endpoint are already covered by unit tests.
> WB-1588 endpoint to check match between reset code and login

- workspace/src/main/resources/view-src/workspace.html
Update LOOL actions display when empty screen (no action on the top bar)
[Ticket WB-2247](https://edifice-community.atlassian.net/browse/WB-2247)
> feat: #WB-2247 Update LOOL actions display when emptyscreen

- auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
- auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java
- common/src/main/java/org/entcore/common/datavalidation/DataValidationService.java
- common/src/main/java/org/entcore/common/datavalidation/impl/AbstractDataValidationService.java
- common/src/main/java/org/entcore/common/datavalidation/impl/DefaultUserValidationService.java
- common/src/main/java/org/entcore/common/sms/SmsSender.java
- Ajout du numéro de téléphone aux événements d'envoi de SMS pour meilleur suivi
- Mise en place de de différentes valeurs de module pour les cas suivants :
- MFA
- validation du numéro de tel
- réinitialisation du mdp
[WB-2329](https://edifice-community.atlassian.net/browse/WB-2329)
[WB-2329]: https://edifice-community.atlassian.net/browse/WB-2329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> [EDIFICE] Ajouter des infos dans les events recoltés sur les SMS

- cas/src/main/java/org/entcore/cas/services/JupyterRegisteredService.java
added an access event for the Jupyter connector. The aim is to be able to report Jupyter connector access statistics in the "Statistics" module.
data example :
```
db.getCollection('events').find({'event-type': 'ACCESS', 'connector-type': 'Cas'})
...
"connector-type" : "Cas",
"event-type" : "ACCESS",
"module" : "JupyterRegisteredService",
"date" : NumberLong(1702636429991),
"userId" : "uuid",
"profil" : "Personnel",
```
[STAT-156](https://jira.support-ent.fr/browse/STAT-156)
[DOC](https://confluence.support-ent.fr/pages/viewpage.action?pageId=54724067#FonctionTransverse:R%C3%A9ponseCAS-Enlocal)
Create a Connector with a simple url like https://google.com or https://github.com
In "Champs spécifiques …
> feat(stats): #STAT-156 add access event for Jupyter connector

- common/src/main/java/org/entcore/common/explorer/IExplorerPluginClient.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginClient.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerPluginClientDefault.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerRepositoryEvents.java
Lorsque le temps de latence sur les replica mongodb est non négligeable, la réindexation après import échoue
Cette petite évo ajoute un mécanisme de retentative de la réindexation tant que celle ci échoue
#Wb2-1367:
- [ X] New feature (MINOR)
- [ X] common
Testé sur une plateforme HA:
- import sur blog
- import sur mindmap
- [ X] All done ! :smiley:
> [EDIFICE] #Wb2-1367: ajout d'un retry pour reindexer les ressources après import

- archive/src/main/java/org/entcore/archive/Archive.java
- archive/src/main/java/org/entcore/archive/services/impl/DeleteOldArchives.java
- common/src/main/java/org/entcore/common/storage/Storage.java
- common/src/main/java/org/entcore/common/storage/impl/FileStorage.java
Ce fix vient renforcer la purge existante sur le module archive en ajoutant une tâche qui vient supprimer tout les fichiers et dossiers dans l'âge de modification dépasse X heures.
Pour cela une config a été ajouté:
- enablePurgeByFileAge (true par défaut) qui active ou non cette nouvelle tâche
- maxFileAge (défaut à 24) le nombre d'heure max de durée d'un fichier ou dossier
#WB2-1173
- [X ] Bug fix (PATCH)
- [X ] archive
- [X ] common
Testé sur une plateforme de recette en
- créant un fichier avec une fausse date de modif dépassant l'age => il est supprimé
- créant un fichier avec une fausse date de modif ne dépassant pas l'age => il est conservé …
> fix: #WB2-1173, make archive purge more reliable

- timeline/src/main/java/org/entcore/timeline/services/impl/DefaultPushNotifService.java
Depuis la version 1.10.0, l’application mobile compte le nombre de notifications push reçues et met à jour le badge sur l’icône de l’application.
Dans certains cas, lors de la réception d’une notification push, ce badge peut brièvement passer à 1 puis réafficher le bon nombre.
https://edifice-community.atlassian.net/browse/MOZO-138
Les tests seront faits dans l'app mobile après déploiement
> chore(timeline): #MOZO-138, remove badge default value from push-notif payload

- directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
- directory/src/main/resources/public/template/dominos-user.html
A user must be able to see all students/tachers in the 'My Class' view regardless of communication rights, but he cannot communicate with them.
https://edifice-community.atlassian.net/browse/MOZO-150
- Se connecter avec un compte 1D parent
- Aller sur la vue "La classe"
- On doit afficher tous les utilisateurs de la classe indépendamment des droits de communication
- Pour les utilisateurs dont on n’a pas le droit de communication, l'icone messagerie n'est pas affichée et la carte utilisateur n'est pas cliquable.
Vérifier la récupération des utilisateurs bloqués:
- Se connecter avec un compte admin et bloquer un utilisateur de la classe (élève ou enseignant)
- Revenir sur le compte du parent et …
> feat(directory): #MOZO-150, show all class users & customize results depending on communication rules

- directory/src/main/resources/i18n/fr.json
- directory/src/main/resources/public/template/class-list.html
- directory/src/main/resources/public/template/class.html
- directory/src/main/resources/public/template/dominos.html
- directory/src/main/resources/public/template/no-classroom.html
- directory/src/main/resources/public/ts/controllers/directory.ts
- directory/src/main/resources/public/ts/model.ts
- If the user has multiple classes, we display the 'class list' in 'The classroom' view.
- If the user has only one classroom, we display the users of the classroom.
- The user can search classroom by name, we display an empty state if no result found.
https://edifice-community.atlassian.net/browse/MOZO-154
https://edifice-community.atlassian.net/browse/MOZO-155
1. Cas multi classe:
Se connecter avec un compte qui a plusieurs classes
=> La vue doit afficher la liste de toutes les classes
=> Le champ "Recherche" doit filtrer les classes affichées par "nom"
=> La recherche abouti un empty state si pas de classe
3. Cas mono classe:
Se connecter avec un compte qui a une seule classe
=> La vue doit par …
> feat(directory): #MOZO-154, #MOZO-155, handle multiple classrooms case

- directory/src/main/resources/i18n/fr.json
- directory/src/main/resources/public/template/class-list.html
- directory/src/main/resources/public/template/no-classroom.html
Change wording/illustration in class empty state view
https://edifice-community.atlassian.net/browse/MOZO-155
- Se connecter avec un compte 1D qui a plusieurs classes
- Aller dans la vue "La classe"
- Lancer une recherche par nom de classe inexistante
- Vérifier que le wording et l'illustration correspondent à la spéc
> feat(directory): #MOZO-155, change wording/illustration in class empty state view

- auth/src/main/java/org/entcore/auth/services/impl/SSOPeertube.java
We want to verify if the user has access to the peertube connector before creating an account with the SAML peertube plugin. We thus added a field in the SSO Peertube answer to retrieve this information in peertube. The field will be set to 'true' if the user has access to the application, or 'false' otherwise
[MEX-347](https://jira.support-ent.fr/browse/MEX-347)
With an account that has access to the connector, make an SSO request to the SSOPeertube response, check in the response if the 'hasConnectorAccess' field is properly filled and has the value 'true'. The same test can be performed with an account that does not have access to the …
> feat(peertube-saml): #MEX-347 Add a field to the SSO response to indicate whether the user has access to the app

- common/src/main/java/org/entcore/common/folders/FolderManager.java
- common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
- common/src/main/java/org/entcore/common/folders/impl/FolderManagerWithQuota.java
- common/src/main/java/org/entcore/common/folders/impl/QueryHelper.java
- common/src/main/java/org/entcore/common/folders/impl/StorageHelper.java
- workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java
- workspace/src/main/java/org/entcore/workspace/security/WorkspaceResourcesProvider.java
- workspace/src/main/java/org/entcore/workspace/service/WorkspaceService.java
- workspace/src/main/java/org/entcore/workspace/service/impl/DefaultWorkspaceService.java
- workspace/src/main/resources/jsonschema/transferDocuments.json
Ce endpoint permet de transférer, en un seul appel, plusieurs documents de l'utilisateur 
* depuis le dossier "Mes documents" ou "Partagés avec moi" 
* vers le pseudo-dossier "Partagé dans mes applis" (visibility=protected) ou "Publics" (visibility=public)
Un tableau de documents est retourné, dans le même ordre que les ids spécifiés dans le corps de la requête. 
Tout document retourné à `null` signifie que son transfert a échoué, ou que le document demandé n'existaient pas.
En interne, si un document est transféré vers l'espace `protected` ou `public`, alors une copie des fichiers est effectuée, et l'original est conservé intact.
S'il passe de `protected` à `public` ou inversement, seule l'indexation en DB change. Les fichiers sont conservés.
Ce comportement imite le fonctionnement …
> feat(workspace): #WB-2679, direct transfer of documents to protected or public space

- auth/src/main/java/org/entcore/auth/services/impl/DefaultMfaService.java
- common/src/main/java/org/entcore/common/datavalidation/DataValidationService.java
- common/src/main/java/org/entcore/common/datavalidation/EmailValidation.java
- common/src/main/java/org/entcore/common/datavalidation/MobileValidation.java
- common/src/main/java/org/entcore/common/datavalidation/UserValidationService.java
- common/src/main/java/org/entcore/common/datavalidation/impl/DefaultUserValidationService.java
- common/src/main/java/org/entcore/common/user/UserInfos.java
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- directory/src/main/resources/i18n/fr.json
- directory/src/main/resources/view-src/email/emailUpdateWarning.html
- directory/src/main/resources/view-src/email/mobileUpdateWarning.html
- directory/src/main/resources/view-src/phone/mobileUpdateWarning.txt
- session/src/main/java/org/entcore/session/AuthManager.java
If the user's mobile phone number has been modified by any means, an email must be sent and an SMS to their old mobile phone number.
https://edifice-community.atlassian.net/browse/MOZO-161
1. Se connecter avec un compte
2. Aller sur la page "Mon compte"
3. Modifier le numéro de téléphone mobile
=> Après validation du code et confirmation, l'utilisateur doit recevoir un mail d'alerte ainsi qu'un sms sur son ancien numéro lui informant que le numéro de téléphone a été modifié.
> feat: #MOZO-161, send warning email & sms to old mobile phone number when it has been modified

- directory/src/main/java/org/entcore/directory/controllers/StructureController.java
Endpoint being protected by DirectoryResourcesProvider
https://edifice-community.atlassian.net/browse/WB-2993
Testé directement sur recette-ode-1
> fix: WB-2993, endpoint already protected by DirectoryResourcesProvider

- common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
- common/src/main/java/org/entcore/common/storage/impl/FileStorage.java
- workspace/src/main/java/org/entcore/workspace/controllers/WorkspaceController.java
Afin d'éviter d'avoir une dépendance sur la création de miniatures, on renvoie désormais l'image original lorsque la miniature demandée n'existe pas encore (mais on lance bien la création de la mnitiature en parallèle).
WB-3046
> [EDIFICE] Send back original image if thumbnail not yet created

- common/src/main/java/org/entcore/common/notification/NotificationUtils.java
- common/src/test/java/org/entcore/common/notification/NotificationUtilsTest.java
Mise à disposition d'une nouvelle fonction permettant de créer les _previews_ à partir du contenu Json généré par TipTap et non plus à partir du HTML. Cela permet de :
- corriger un bug concernant les pièces jointes qui n'étaient plus reconnues par le parser actuel
- rendre le code de génération plus lisible (on se débarasse des regexp)
WB-3073
Les tests ajoutés dans les TUs
> [EDIFICE] Use tiptap transformer generated json content to create previews

- auth/src/main/java/org/entcore/auth/services/impl/SSOGLPI.java
Suite au ticket https://edifice-community.atlassian.net/browse/CGIDEV-74, où l'urgence était d'établir la connexion SAML pour le service GLPI en utilisant la réponse SSOPeertube en raison de contraintes de temps, une demande avait initialement été faite par GLPI pour adapter les réponses en fonction de leurs exigences (https://jira.support-ent.fr/browse/CS-7). Par conséquent, nous avons construit une réponse dédiée à GLPI.
[(Ticket CGI)](https://jira.support-ent.fr/browse/CS-7)
Pour tester la réponse, on a remplacé la réponse `SSOPeertube` du module auth par `SSOGLPI`
```
"saml-services-providers":{
"https://${host}/plugins/auth-saml2-cgi/router/metadata.xml":"org.entcore.auth.services.impl.SSOGLPI" …
```
> feat(GLPI): #CS-7 create new SAML response for GLPI service

- app-registry/src/main/java/org/entcore/registry/controllers/LibraryController.java
- app-registry/src/main/java/org/entcore/registry/services/impl/DefaultLibraryService.java
- portal/src/main/resources/i18n/fr.json
Render HTTP 413 error (Content Too Large) when Library backend returns that error to display a specific error message to the user.
Related to https://github.com/edificeio/edifice-ui/pull/194
https://edifice-community.atlassian.net/browse/WB2-1747
> fix(app-registry): #WB2-1747, handle Content Too Large error in Library publishing

- archive/src/main/java/org/entcore/archive/services/impl/DefaultDuplicationService.java
- common/src/main/java/org/entcore/common/explorer/ExplorerMessage.java
- common/src/main/java/org/entcore/common/explorer/ResourceDuplicatedMessage.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerResourceDetails.java
- common/src/main/java/org/entcore/common/explorer/impl/ExplorerResourceDetailsQuery.java
Après la duplication d'une ressource, nous générons désormais un message Explorer afin de déplacer la ressource nouvellement créée dans le bon dossier.
WB2-1733
1. Créer une ressource dans un dossier
2. Dupliquer cette ressource
3. Raffraîchir la page
4. Constater que cette ressource n'est pas à la racine
5. Se déplacer dans le dossier cible
6. Constater que la ressource dupliquée est bien dans le dossier
> feat: #WB2-1733, move a resource to the right folder after duplicating it

- common/src/main/java/org/entcore/common/storage/impl/FileStorage.java
Fixing regression on file storage with nullity check on metadata.
It is necessary when sendFile() is called from ArchiveController, to export an archive.
No dedicated ticket : discovered when trying to run integration tests, it made one archive scenario fail.
Running integration tests
> fix: checking metadata nullity for archive export

- feeder/src/main/java/org/entcore/feeder/ManualFeeder.java
- feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
- feeder/src/main/java/org/entcore/feeder/dictionary/structures/User.java
The pre deletion of ADML users of structures with many sub structures raises an exception in Neo4J because we try to set a value too large for the field IN_OUTGOING of the backup node.
To prevent this from happening, we now (conditionnally) do not backup ADML related relationships. It makes the value for the field IN_OUTGOING smaller and so no exception is raised. On the other hand, upon restoration, users ADML rights are not brought back but it is functionnaly sound.
WB-2962
1. Add ADML test to a user in admin console
2. Pre-delete the user
3. Execute the following request and check that no AdminLocal groups are fetched
```cypher
MATCH (u:User{login: "catherine.bailly"})-->(backup:Backup) return …
```
> [EDIFICE] Do not backup adml related relationships when backuping a user about to be deleted

- feeder/src/main/java/org/entcore/feeder/dictionary/structures/DuplicateUsers.java
The pre deletion of ADML users of structures with many sub structures raises an exception in Neo4J because we try to set a value too large for the field IN_OUTGOING of the backup node.
To prevent this from happening, we now (conditionnally) do not backup ADML related relationships. It makes the value for the field IN_OUTGOING smaller and so no exception is raised. On the other hand, upon restoration, users ADML rights are not brought back but it is functionnaly sound.
WB-2962
1. Add ADML test to a user in admin console
2. Pre-delete the user
3. Execute the following request and check that no AdminLocal groups are fetched
```cypher
MATCH (u:User{login: "catherine.bailly"})-->(backup:Backup) return …
```
>  [EDIFICE] Do not backup adml related relationships when backuping a user about to be deleted

- common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
- directory/src/main/java/org/entcore/directory/controllers/UserPositionController.java
- tests/src/test/js/it/scenarios/position/crud.js
Lors d'une tentative de création de fonction existante, on renvoie désormais une erreur 409 avec l'id de la position existante dans le body.
WB-3301
Ajout d'un TI dans crud.js
> [EDIFICE] send back a 409 error code if we try to create a function that already exists

- feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
Ne pas créer de noeud de backup pour les utilisateurs lors de la transition d'année. Seuls les mécanismes de suppression, pré-suppression et fusion par clef devraient générer des noeuds de Backup.
WB-3274
> [EDIFICE] Do not backup users when transitionning

- admin/src/main/ts/proxy-development.conf.js
- admin/src/main/ts/src/app/app-routing.module.ts
- admin/src/main/ts/src/app/core/core.module.ts
- admin/src/main/ts/src/app/core/resolvers/favicon.resolver.ts
- admin/src/main/ts/src/app/core/store/mappings/theme.ts
- admin/src/main/ts/src/app/core/store/models/session.model.ts
- admin/src/main/ts/src/app/management/message-flash/message-flash.service.ts
- admin/src/main/ts/src/app/navbar/navbar.component.ts
Admin console v2 was showing the default Angular icon.
Now it displays the one from user's skin.
NE PAS MERGER, c'est pour une version future....
[WB-1069](https://edifice-community.atlassian.net/browse/WB-1069)
1. Connect to /admin
2. Check the displayed icon in browser tab.
[WB-1069]: https://edifice-community.atlassian.net/browse/WB-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(admin): #WB-1069, add themed favicon to admin console

- admin/src/main/resources/i18n/fr.json
- common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
- directory/src/main/java/org/entcore/directory/controllers/UserPositionController.java
- tests/src/test/js/it/scenarios/position/crud.js
Lorsque l'on tente de renommer une fonction, on vérifie désormais qu'il n'existe pas déjà une fonction portant le même nom dans le même établissement.
WB-3323
> fix: #WB-3323, do not allow renaming of positions with an already taken name in the same structure

- directory/src/main/java/org/entcore/directory/security/DirectoryResourcesProvider.java
- tests/src/test/js/it/scenarios/position/attribute-position.js
Vérifier les champs qui vont être mis à jour quand on appelle la méthode de MàJ d'un utilisateur pour savoir si on a le droit de laisser passer l'appel.
WB-3330
> [EDIFICE] Allow ADML users to update other ADMLs functions

- admin/src/main/ts/src/app/_shared/user-position-modal/user-position-modal.component.html
- admin/src/main/ts/src/app/core/resolvers/favicon.resolver.ts
- admin/src/main/ts/src/app/users/create/user-create.component.html
- admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.html
- directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
- feeder/src/main/java/org/entcore/feeder/ManualFeeder.java
- tests/src/test/js/it/scenarios/position/run.sh
- tests/src/test/js/it/scenarios/position/user-creation.js
* Creating a Personnel attached to a list of UserPositions must be allowed, but they were filtered out by Feeder.
* Some buttons were acting as submit buttons and validating forms prematuraly.
* Removed some unnecessary logs.
[WB-3332](https://edifice-community.atlassian.net/browse/WB-3332)
[WB-3332]: https://edifice-community.atlassian.net/browse/WB-3332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> fix(admin,feeder,directory): #WB-3332, allow creating a Personnel with a list of UserPositions

- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/src/app/core/services/userlist.filters.service.ts
- admin/src/main/ts/src/app/core/store/models/structure.model.ts
- admin/src/main/ts/src/app/core/store/models/user.model.ts
- admin/src/main/ts/src/app/structure/structure.resolver.ts
- admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.ts
- admin/src/main/ts/src/app/users/users-list/users-list.component.ts
- directory/src/main/java/org/entcore/directory/services/impl/DefaultSchoolService.java
- directory/src/main/resources/public/template/favorite-form.html
Feature to filter user list in admin console by new user position field
[WB-3302](https://edifice-community.atlassian.net/browse/WB-3302)
* Open admin console as ADMC
* Choose a structure
* Open the Users menu
* Add positions to a user attached to the structure
* Open the users filters
* Filter on one of the positions
* Check that the users list is correctly filtered
[WB-3302]: https://edifice-community.atlassian.net/browse/WB-3302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> feat(admin): #WB-3208 #WB-3207 add filter with user position

- common/src/main/java/org/entcore/common/sql/ISql.java
- common/src/main/java/org/entcore/common/sql/Sql.java
Implémentation d'une méthode "prepare" pour l'exécution du requête SQL qui renvoit un Future plutôt que de prendre un Handler en param.
https://edifice-community.atlassian.net/browse/WB-2579
> fix: WB-2579, add prepare query returning a future

- common/src/main/java/org/entcore/common/folders/FolderManager.java
- common/src/main/java/org/entcore/common/folders/impl/FolderImporterZip.java
Use `import-path` variable to specify the import location to unzip imported archives.
WB-3352
1. Import zip archive in "Mes données"
2. Check that the zip is unzipped in the specified location
> [EDIFICE] Use import-path configuration value to store zip file being imported

- infra/src/main/java/org/entcore/infra/Starter.java
- infra/src/main/java/org/entcore/infra/metrics/MicrometerInfraMetricsRecorder.java
Création d'un nouveau metricsrecorder pour diffuser une métrique basée sur le numéro de version de l'ENT.
Elle a le format suivant :
- sans point
- avec 2 chiffres par emplacement
WB-3251
> [EDIFICE] Exposer le numéro de version de l'ENT via une métrique

- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- directory/src/main/java/org/entcore/directory/services/UserService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
- tests/src/test/js/it/scenarios/admin/utils.js
- tests/src/test/js/it/scenarios/isolated_users/list.js
- tests/src/test/js/it/scenarios/isolated_users/run.sh
Réhabiliter le tri paramétrable sur la méthode DefaultUserService.listIsolated().
Ajouter des tests d'intégration.
[WB-1699](https://edifice-community.atlassian.net/browse/WB-1699)
* Via Postman `/directory/list/isolated`
Le tri custom ne semble pas utilisé dans l'ENT.
[WB-1699]: https://edifice-community.atlassian.net/browse/WB-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(directory): WB-1699, restore custom sort on listIsolated method

- auth/src/main/java/org/entcore/auth/controllers/AuthController.java
- auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java
- auth/src/main/java/org/entcore/auth/users/UserAuthAccount.java
- auth/src/main/resources/view-src/activation.html
Lors de la 1ère connexion d'un utilisateur, la vérification du couple (login, code activation) retournait un booléen, pour signifier si un utilisateur concordant avait bien été identifié ou non.
Désormais, cette vérification remonte aussi des méta-données supplémentaires, comme l'adresse email ou le n° de mobile. Ces données sont ensuite transmises au frontend qui peut pré-remplir le formulaire d'activation au mieux, et laisser le choix à l'utilisateur de les modifier.
Si le flux d'activation de compte fonctionne comme avant (au détail près que le formulaire est possiblement pré-rempli), beaucoup de refacto de code a été nécessaire pour pouvoir remonter les méta-données de bout-en-bout.
[WB-3220](https://edifice-community.atlassian.net/browse/WB-3220)
Please check options that are …
> feat(auth): WB-3220, prefill activation form with email and mobile

- auth/src/main/java/org/entcore/auth/controllers/AuthController.java
- auth/src/main/java/org/entcore/auth/users/DefaultUserAuthAccount.java
- auth/src/main/java/org/entcore/auth/users/UserAuthAccount.java
- auth/src/test/java/org/entcore/auth/UserAuthAccountTest.java
Prise en compte du feedback d'Intégration :
* Rétablit l'interface UserAuthAccount avec des handlers, modifiés pour répondre à mon besoin, et supprime les Futures trop évolués pour cette interface.
* Conserve cet [algo sous forme de composition de Futures](https://github.com/edificeio/entcore/blob/d8bcf2aa9e02607a4f331375c5d512d8d65a5e68/auth/src/main/java/org/entcore/auth/controllers/AuthController.java#L753), à l'identique. Il y a des tests auto en Java sur cette partie.
- Unit tests were added …
> fix(auth): #WB-3220, late feedback from PR 537

- admin/src/main/ts/src/app/_shared/user-position-modal/user-position-modal.component.ts
- admin/src/main/ts/src/app/core/core.module.ts
- admin/src/main/ts/src/app/core/services/user-position.service.ts
- admin/src/main/ts/src/app/core/store/models/structure.model.ts
- admin/src/main/ts/src/app/management/management-root/management-root.component.ts
- admin/src/main/ts/src/app/management/structure-user-positions/structure-user-position/structure-user-position.component.ts
- admin/src/main/ts/src/app/management/structure-user-positions/structure-user-positions.component.ts
- admin/src/main/ts/src/app/users/create/user-create.component.html
- admin/src/main/ts/src/app/users/create/user-create.component.ts
- admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.html
- admin/src/main/ts/src/app/users/details/sections/user-positions/user-positions-section.component.ts
- common/src/main/java/org/entcore/common/user/position/UserPositionService.java
- common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
- directory/deployment/directory/conf.j2
- directory/src/main/java/org/entcore/directory/Directory.java
- directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
- directory/src/main/java/org/entcore/directory/controllers/UserController.java
- feeder/src/main/java/org/entcore/feeder/Feeder.java
- portal/src/main/resources/i18n/fr.json
Ajout d'une conf plateforme pour empêcher les ADML de créer/modifier/supprimer des nouvelles fonctions (UserPosition)
* Vérification de la valeur du paramètre côté back avant tout CRUD
* Côté front, si la conf est activée :
* Boutons de création masqués
* Onglet de management masqué
* Les ADML multi-établissement ne peuvent plus voir que les fonctions de l'établissement courant.
Les ADML peuvent toujours affecter et retirer des fonctions parmi celles qui existent dans leur établissement.
+ code cleanup
[WB-3374](https://edifice-community.atlassian.net/browse/WB-3374)
1. Manual tests only
- Unit tests were added and/or …
> feat(common,directory,admin): WB-3374, new parameter to restrict CRUD operations on UserPosition

- directory/src/main/java/org/entcore/directory/security/DirectoryResourcesProvider.java
La récupération des données userBook des utilisateurs depuis un compte ADML ne fonctionnait plus depuis [ce commit](https://github.com/edificeio/entcore/commit/1756a563317a8d4d7251cb13923a2d667000076b) car on tentait de récupérer le corps de la requête en JSON. Cependant, pour certaines requêtes il n'y a pas de corps et notamment pour celle de récupération des informations userBook. 
[WB-3376](https://edifice-community.atlassian.net/browse/WB-3376)
1. Se connecter avec un ADML (et non pas un ADMC)
2. Appeler l'url /directory/userbook/{idUser}
3. Constater que l'on récupère bien des infos
- Unit tests were added and/or …
> [EDIFICE] Do not try to parse body when no body is present

- common/src/main/java/org/entcore/common/user/position/UserPosition.java
- feeder/src/main/java/org/entcore/feeder/csv/CsvFeeder.java
- tests/src/test/js/it/scenarios/position/csv-import.js
- tests/src/test/resources/data/positions/csv/after/enseignants.csv
Lors d'un import CSV, les fonctions au "format libre" sont en fait converties dans des étapes préliminaires à l'import en un format pseudo-AAF (séparateur avec des dollars mais informations vides : $$$[FunctionName]).
On prend désormais également ce cas en compte dans l'implémentation.
Cela corrige aussi le problème lié de la création des groupes de fonction pour les seuls formats AAF complets.
https://edifice-community.atlassian.net/browse/WB-3409
https://edifice-community.atlassian.net/browse/WB-3417
Updated integration tests and manual tests performed
- I have updated the reminder …
> fix : checking functions with not fully filled pseudo AAF format

- admin/src/main/resources/i18n/fr.json
- admin/src/main/ts/src/app/core/services/userlist.filters.service.ts
- admin/src/main/ts/src/app/users/users-list/users-list.component.ts
Suite au chantier fonctions, le filtre utilisateur "Fonctions et matières" doit présenter les matières uniquement.
- On le renomme en conséquence
- On limite son contenu aux seules "matières" (clé ENS dans les AAFs)
- On déplace le nouveau filtre "Fonctions" à proximité de "Matières" afin que les end-users s'y retrouvent facilement. 
[WB-3416](https://edifice-community.atlassian.net/browse/WB-3416)
[WB-3416]: …
> feat(admin): #WB-3416, limit aafFunctions filter to ENS functions

- common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
- feeder/src/main/java/org/entcore/feeder/aaf/PersonnelImportProcessing.java
- feeder/src/main/java/org/entcore/feeder/aaf/PersonnelImportProcessing2.java
- feeder/src/main/java/org/entcore/feeder/aaf1d/PersonnelImportProcessing1d.java
- feeder/src/main/java/org/entcore/feeder/csv/CsvFeeder.java
- feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
On détache toutes les fonctions AAF de chaque utilisateur avant de créer celles provenant du fichier en cours d'import.
À la fin de l'import, toutes les fonctions AAF  attachées à aucun utilisateur sont supprimées (déjà implémenté).
https://edifice-community.atlassian.net/browse/WB-3419
Tests dev manuels & relance des tests d'intégration K6 associés
> fix : detaching aaf positions before aaf import

- admin/src/main/ts/src/app/_shared/user-position-modal/user-position-modal.component.ts
- common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
Il était possible de créer des doublons de UserPositions, en saisissant des espaces avant ou après leur nom.
Ce fix corrige la faille.
[Ticket WB-3429](https://edifice-community.atlassian.net/browse/WB-3429)
> fix(admin,common): #WB-3429, trim UserPosition names before saving

- tests/src/main/scala/org/entcore/test/scenarios/AuthScenario.scala
Le test d'inté "Auth Scenario / Get OAuth2 code with disconnected user" est en erreur lors d'une exécution sur SB local.
Le message remonté est "status.find.is(200), but actually found 302"
A priori, il s'agirait d'un effet de bord du traitement du ticket "support 1264". 
@dbreyton , tu confirmes ? Cette PR serait alors un fix possible.
[SUPPORT-1264](https://edifice-community.atlassian.net/browse/SUPPORT-1264)
[SUPPORT-1264]: …
> fix(tests): #SUPPORT-1264, fix integrationTests

- admin/src/main/ts/src/app/core/services/userlist.filters.service.ts
- admin/src/main/ts/src/app/groups/details/manage-users/input/group-input-filters/group-input-filters.component.ts
- admin/src/main/ts/src/app/users/users-list/users-list.component.ts
There is an issue with search the component ode-multi-combo when passing Array<Array<sting>> the search won't work.
I update the list type to have an Array of string which work fine.
> fix(admin): #WB-59 filter fonction in user liste

- directory/src/main/java/org/entcore/directory/security/DirectoryResourcesProvider.java
An ADML can now access the userbook information of another ADML
Fixing an indirect problem discovered during the investigation on this : https://edifice-community.atlassian.net/browse/WB-3378
> fix : WB-3378, make motto visible among local admins

- feeder/src/main/java/org/entcore/feeder/dictionary/structures/DuplicateUsers.java
- tests/src/test/js/it/scenarios/position/crud.ts
Lorsque l'on merge deux comptes adml dupliqués, désormais on ne crée qu'une **unique** relation `HAS_FUNCTION` vers le noeud de la Fonction ADML, et cette relation a pour scope l'union des scopes de structure pour lesquels les deux comptes avaient la fonction ADML.
https://edifice-community.atlassian.net/browse/WB-3640
Un test d'intégration k6 associé à ce bugfix a été ajouté
> Fix wb 3640 single has function after merging admls

- common/src/main/java/org/entcore/common/share/impl/GenericShareService.java
- common/src/main/java/org/entcore/common/user/UserUtils.java
Lorsque les favoris de partage contiennent un nombre important d'utilisateurs, la requête de recherche des utilisateurs visibles peut atteindre un timeout.
Actions réalisées : 
- élévation de la limite du timeout pour l'appel à la méthode findVisibles (30s → 1m)
- mise en parallèle de l'appel à la méthode findVisible par lots d'id
Avec ces changements on parvient à répondre dans cas reproductible en recette-release : le partage à un favoris contenant plus de 4000 utilisateurs.
https://edifice-community.atlassian.net/browse/WB-3666
Tests manuels directement sur recette-release (environnement pour lequel le bug était reproductible)
- Unit tests were …
> fix: WB-3666, optimize voluminous shares request

- conversation/frontend/src/components/ProgressBar.css
- conversation/frontend/src/components/ProgressBar.tsx
- conversation/frontend/src/components/index.ts
- conversation/frontend/src/features/Menu/components/DesktopMenu.tsx
- conversation/frontend/src/hooks/index.ts
- conversation/frontend/src/hooks/useUsedSpace.ts
- portal/src/main/resources/i18n/fr.json
The ProgressBar component should evolve in a future lot, to include more details.
WB-3434
none
> feat(conversation): #WB-3434, progress bar component,  displaying the used storage space compared to the allowed quota

- common/src/main/java/org/entcore/common/events/EventHelper.java
Do not create ACCESS EVENT for mobile webview. The ACCESS EVENT is handled already via the app so it was redundant to also create an ACCESS EVENT for the webview.
Mobile webview uses the `xApp=mobile` query param, so if the param is present then we do not create ACCESS EVENT.
This behaviour will be applied to all mobile apps using webview so that's why we consider the `onAccess` method of the `EventHelper` to be the right place to handle this.
- I have …
> fix(common): #WB2-1957, skip creating ACCESS EVENT for mobile webview

- common/src/main/java/org/entcore/common/share/impl/GenericShareService.java
- tests/src/test/js/it/scenarios/workspace/share.ts
Au moment de partager une ressource via un favori de partage, depuis ce [ticket](https://edifice-community.atlassian.net/browse/WB-2242) on vérifie les droits de communication (techniquement les "visibles").
Si on perd les droits de partage vers un des membres du favori (utlisateur ou groupe), le partage est impossible. Ça n'est pas un comportement souhaité.
Désormais on récupère la liste des utilisateurs ou groupes visibles (pour lesquels on a les droits de com) et on n'effectue le partage que pour les membres du favoris de partage qui sont visibles.
PR associée : https://github.com/edificeio/edifice-k6-commons/pull/5
https://edifice-community.atlassian.net/browse/WB-3639
Tests d'intégration K6
Test …
> fix: WB-3639, filter shares with visible users and groups

- conversation/backend/src/main/resources/i18n/fr.json
- conversation/frontend/src/features/Menu/components/MobileMenu.tsx
- conversation/frontend/src/features/Modals/RenameFolderModal.test.tsx
- conversation/frontend/src/mocks/index.ts
- conversation/frontend/src/models/folder.ts
- conversation/frontend/src/services/queries/folder.ts
Tests de la modale de renommage de dossier.
+ modification d'un wording décidé la semaine dernière
[WB-3454](https://edifice-community.atlassian.net/browse/WB-3454)
- `should render successfully`: Verifies that the component renders correctly with required elements.
- `should forbid renaming a folder named with only blank characters`: Ensures that renaming a folder with only blank characters triggers an error toast.
- `should forbid renaming a folder with the same name as another folder`: Ensures that renaming a folder with a duplicate name triggers an error toast.
- `should rename a folder`: Ensures that creating a folder with a valid name triggers a success toast.
- Performance …
> feat(conversation): #WB-3454, tests for the rename folder modal

- conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
- pom.xml
In order to correctly format the former conversation history, a [new dedicated tip tap extension](https://github.com/edificeio/edifice-frontend-framework/commit/8ef0c3a4cb7e5dd05d680dd92040bda109df30e8) has been implemented.
This extension must be applied only for conversation content transformation, and an evolution in the content transformer client has been made to do so.
Related PR : 
- https://github.com/edificeio/edifice-tiptap-transformer/pull/21
- https://github.com/edificeio/web-utils/pull/33
https://edifice-community.atlassian.net/browse/WB-3821
- Unit tests …
> feat: WB-3821, requesting conversation-specific content transformations

- conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
- conversation/backend/src/main/resources/sql/019-conversation-originalmessages.sql
- tests/src/test/js/it/scenarios/conversation/transform.ts
Lorsqu'on appelle la nouvelle api de récupération des détails d'un message, on remonte l'information sur l'existence ou non du format original du message (avant transformation tiptap) dans un champ `original_format_exists`
Cela permet au front d'afficher le bouton d'affichage de l'ancien format seulement si nécessaire.
En testant sur ode1, ce cas a révélé qu'il manquait des privilèges pour le user "apps" sur la table conversation.originalmessages. 
https://edifice-community.atlassian.net/browse/WB-3837
Enrichissement des TI k6 associés
Par la nature même des TI, on ne peut pas avoir de cas de messages pour lesquels un format original préexiste.
Le cas avec format original préexistant a été testé …
> Feat wb 3837 original format existence

- .gitignore
- build.sh
- gulpfile.js
Now that we moved from gradle to maven, gulp `watch` task cannot leverage the properties of gradle.properties to get he name of the module to build. This PR fixes that by :
1. adding a step right before the gulp task is launched that will call `mvn` to output the module name to watch in a temporary file `.version.properties`
2. modifying the task `watch` by reading from `.version.properties` instead of `gradle.properties`
3. removing the `.version.properties` after the `watch` task is done
ENABLING-217
> fix(dev): #ENABLING-217, fetch modname from pre exported module version for js watch

- common/src/main/java/org/entcore/common/share/impl/GenericShareService.java
Correction d'une NPE qui survient lorsqu'un verticle n'a pas appelé `EventStoreFactory.getFactory().setVertx(vertx)` avant d'instantier un `ShareService`.
SUPPORT-2556
Vérifier que le job `CreateDailyPresenceWorker` s'exécute bien.
> fix: #SUPPORT-2556, fix NPE while initializing GenericShareService for workers deployed by other verticles

- common/src/main/java/org/entcore/common/conversation/LegacySearchVisibleRequest.java
- common/src/main/java/org/entcore/common/user/UserUtils.java
- communication/src/main/java/org/entcore/communication/Communication.java
- communication/src/main/java/org/entcore/communication/controllers/CommunicationController.java
- communication/src/main/java/org/entcore/communication/services/CommunicationService.java
- communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
- communication/src/test/java/org/entcore/communication/services/impl/DefaultCommunicationServiceTest.java
- communication/src/test/java/org/entcore/communication/services/impl/OptimComTest.java
- conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
- directory/src/main/resources/public/ts/controllers/directory.ts
- pom.xml
- tests/src/test/js/it/scenarios/communication/_search-visibles-legacy.ts
- tests/src/test/js/it/scenarios/communication/_search-visibles-light.ts
- tests/src/test/js/it/scenarios/communication/_utils.ts
- tests/src/test/js/it/scenarios/communication/search_visibles.sh
Nouvelle API de recherche des utilisateurs visibles.
On utilise par défaut la version allégée.
Si besoin de désengager cette nouvelle API car les perfs sont problématiques, l'ancienne API a été adaptée pour retourner les informations au même format que la nouvelle API.
À cause d'un rebase de la branche `develop-b2school` sur `dev`, un nouvelle branche pour feat-WB-3801 a été créée à partir de la version à jour de `develop-b2school`.
La PR associée à la branche initiale : https://github.com/edificeio/entcore/pull/603
https://edifice-community.atlassian.net/browse/WB-3801
Tests dev manuels et tests k6 de présence des champs legacy vs light
- Unit …
> Feat wb 3801 adapt legacy visibles

- common/src/main/java/org/entcore/common/http/BaseServer.java
- common/src/main/java/org/entcore/common/sql/DB.java
- directory/src/main/java/org/entcore/directory/controllers/DirectoryController.java
- directory/src/main/java/org/entcore/directory/services/UserService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
* Add a hook for running post-SQL scripts tasks, in entcore/common BaseServer class
* Add a bus-callable method to get details on users' structures, in directory
Both are a requirement of [PR 40 of OPEN-ENT-NG/actualites](https://github.com/OPEN-ENT-NG/actualites/pull/40)
[WB-1404](https://edifice-community.atlassian.net/browse/WB-1404)
Tests manuels uniquement, avec débogueur pas à pas.
[WB-1404]: https://edifice-community.atlassian.net/browse/WB-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> feat(common,directory): #WB-1404, framework extension for actualites app requirements

- portal/src/main/resources/i18n/en.json
- portal/src/main/resources/i18n/fr.json
This pull request includes updates to the internationalization (i18n) files for the English and French languages. The changes involve adding a new translation key for "appointments" in both languages.
Updates to i18n files:
* [`portal/src/main/resources/i18n/en.json`](diffhunk://#diff-48858710d91e45e1a1fe11bdbcef69638245d208ec2e78d37c96a0c13b3f3c2aR14): Added the translation key "appointments" with the value "Appointments".
* [`portal/src/main/resources/i18n/fr.json`](diffhunk://#diff-73555a44993276414f2f58382f463fb22cc3ddacdf634db93a51a30cfef2aab1R27): Added the translation key "appointments" with the value "Rendez-vous".
1. Describe here the tests you …
> feat(portal): add appointments i18n

- conversation/frontend/src/components/DisplayActionDropDown.tsx
- conversation/frontend/src/features/message/MessageNavigation.tsx
- conversation/frontend/src/features/message/index.tsx
Il y a 2 listes d'actions disponible dans la vue détail du message.
Une en haut situé dans un bandeau de navigation avec toutes les actions possible par rapport au message courant. Avec un séparateur entre "répondre à tous et transférer" des autres actions.
Une liste en bas de message juste avec "répondre, répondre à tous et transférer".
> feat(conversation):#WB-3826 navigation bar and dropdown action list on message detail

- conversation/backend/src/main/resources/i18n/fr.json
- conversation/frontend/src/components/DisplayActionDropDown.tsx
- conversation/frontend/src/components/MessageBody.tsx
- conversation/frontend/src/components/message-attachments/MessageAttachment.tsx
- conversation/frontend/src/components/message-attachments/index.test.tsx
- conversation/frontend/src/components/message-attachments/index.tsx
- conversation/frontend/src/features/message-edit/index.tsx
- conversation/frontend/src/hooks/useMessageAttachments.tsx
- conversation/frontend/src/services/api/attachmentService.test.ts
- conversation/frontend/src/services/api/attachmentService.ts
- conversation/frontend/src/services/api/index.ts
- conversation/frontend/src/services/api/messageService.test.ts
- conversation/frontend/src/services/api/messageService.ts
- conversation/frontend/src/services/queries/attachment.ts
- conversation/frontend/src/services/queries/message.ts
Ajout ou suppression de pièces jointes dans un message en brouillon.
J'ai modifié le hook useCreateOrUpdateDraft, et ai eu un conflit lors de l'ouverture de cette PR.
=> bien vérifier si la navigation vous parait correcte.
[WB-3925](https://edifice-community.atlassian.net/browse/WB-3925)
* Test que l'URL adéquate est appelée par le service d'ajout de PJs. 
[WB-3925]: https://edifice-community.atlassian.net/browse/WB-3925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(conversation): #WB-3925, add or remove attachments to draft messages

- conversation/frontend/src/features/message-list/MessageList.test.tsx
- conversation/frontend/src/features/message-list/MessageList.tsx
- conversation/frontend/src/features/message-list/hooks/useToolbarVisibility.ts
- remove useless gap 
- hide emptytrash when a message is selected
- hide toolbaritem span on mobile
> fix(conversation):#WB-3957-empty trash button

- common/src/main/java/org/entcore/common/share/impl/GenericShareService.java
- docker-compose.yml
- tests/src/test/js/it/scenarios/workspace/share.ts
Faire en sorte de bien prendre en compte les partages existants mais sur lesquels l'utilisateur n'a pas de visiblité lors de la mise à jour des droits de partage.
WB-3639
Mise à jour du test d'inté `testSharesViaProfileGroupInDifferentSchools` qui correspond au cas problématique pour y ajouter la vérification que les partages existants persistent bien.
> fix(common): #WB-3639, do not remove existing shares from users and groups that a share updater cannot see

- conversation/frontend/src/components/SignatureEditor/components/SignatureEditor.tsx
- conversation/frontend/src/components/SignatureEditor/components/SignatureEditorToolbar/SignatureEditorToolbar.tsx
- conversation/frontend/src/features/modals/SignatureModal.tsx
Derniers ajustements demandés : 
* Si la signature n’est pas activé, on doit pouvoir modifier la signature quand même 
* Quand j'écris du texte et que j’atteins le quota maximum de caractères disponible >
** le compteur de caractère qui doit devenir rouge pour indiquer l’erreur
** le bouton d’enregistrement doit être disable
* Quand je copie colle du texte et que j’atteins le quota maximum de caractères autorisé
** le texte copié est collé dans son entièreté
** le quota de la signature affiche le nombre de caractères utilisés / 800 caractères en rouge
** Le bouton de sauvegarde est disable
* Quand on clique sur gras ou italique, on doit avoir un surlignage sur ces icônes pour avertir le user que le mode graisse ou italique est activé …
> fix(conversation): #WB-3441, feedback from free tests

- conversation/backend/src/main/java/org/entcore/conversation/service/ConversationService.java
- conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
- conversation/backend/src/main/resources/i18n/fr.json
- conversation/frontend/src/components/MessageBody.tsx
- conversation/frontend/src/features/message/message-header/index.tsx
Itération agile sur le rappel de messages : 
on souhaite désormais que les émetteurs puissent consulter les messages qu'ils ont rappelés, afin de pouvoir copier/coller le texte.
Cela nécessite de pouvoir retrouver ces messages dans les listes.
Coup de chance, on dispose d'une nouvelle API pour lister les messages, donc j'ai pu rajouter les messages _state=RECALL_ sans casser l'ancienne API, laquelle ne renvoie que les _state=SENT_.
Ajout aussi d'une trads pour les titres des messages rappelés, en vue détails.
WB-3776
- Unit tests were added …
> feat(conversation): #WB-3776, new API allows listing of RECALLed messages

- common/src/main/java/org/entcore/common/user/UserUtils.java
- communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
Cette PR vise à corriger une régression dans la messagerie,  issue de l'utilisation de la nouvelle API de recherche des visibles :
* on n’a pas la liste de diffusion lorsqu’on la recherche en destinataire 
* ni la recherche pas discipline ou fonction ou groupe de profil qui fonctionne,
alors qu’en prod, ça marche.
L'idée est de ré-inclure les groupes dans la requête Neo4j, comme fait dans l'API d'origine.
Or, il faudrait aussi les filtrer par nom, mais certains groupes ont une clé de trad à la place d'un nom en BDD.
On est donc obligé de récupérer les traductions de noms des groupes, avant de pouvoir filtrer dessus.
Comme l'API n'accepte pas la pagination des résultats, l'implémentation proposée fonctionne partiellement : 
il reste que l'ordre de tri des résultats est un peu aléatoire... …
> fix(communication): #WB-3801, add visible groups while filtering by name

- conversation/frontend/src/features/message-edit/components/MessageEditHeader.tsx
- conversation/frontend/src/hooks/index.ts
- conversation/frontend/src/hooks/useAdditionalRecipients.ts
- conversation/frontend/src/routes/pages/Message.tsx
- conversation/frontend/src/routes/redirections/index.tsx
- conversation/frontend/src/services/api/userService.ts
- conversation/frontend/src/services/queries/user.ts
* Prend en compte les raccourcis de création d'un nouveau message (`#write-mail/....`)
* Ajoute des User / Group / Bookmark en destinataire, à l'aide de query-params
L'URL attendue est de la forme `conversation/draft/create?user=userId&group=groupId1&favorite=favoriteId1`
Les query params multiples sont pris en compte.
* Supprime les destinataires en doublon
[WB-3999](https://edifice-community.atlassian.net/browse/WB-3999) …
> feat(conversation): #WB-3999, reroute '#write-mail'-like URLs

- conversation/frontend/src/components/MessageAttachments/MessageAttachments.tsx
- conversation/frontend/src/services/queries/message.ts
[Ticket](https://edifice-community.atlassian.net/jira/software/c/projects/WB/boards/234?assignee=712020%3Aa351bfd8-8169-43e4-821c-48991f7e3d43&selectedIssue=WB-4093)
- On ne doit pas avoir le bloc de PJ visible sur un message sans PJ
- ne pas afficher une piece jointe ajoutée sur un nouveau message precedent
- animer le loader lors de l’ajout d’une piece jointe
> fix(conversation)-WB-4093 fix message-attachements

- common/src/main/java/org/entcore/common/user/UserUtils.java
- communication/src/main/java/org/entcore/communication/controllers/CommunicationController.java
- communication/src/main/java/org/entcore/communication/services/CommunicationService.java
- communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
- directory/src/main/java/org/entcore/directory/Directory.java
- directory/src/main/java/org/entcore/directory/controllers/ShareBookmarkController.java
- directory/src/main/java/org/entcore/directory/services/ShareBookmarkService.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultShareBookmarkService.java
Si les règles de communication ont été modifiées, et qu'un groupe ou un utilisateur dans mes favoris de partage n'est plus visible,
alors la requête `GET /directory/sharebookmark/:bookmarkId` ne doit plus retourner ces users ou groupes non-visibles.
[WB-4022](https://edifice-community.atlassian.net/browse/WB-4022)
[WB-4022]: https://edifice-community.atlassian.net/browse/WB-4022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
> fix(directory,common,communication): #WB-4022, exclude non-visible users from sharebookmarks

- conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
- conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx
* Modifier l'objet du message uniquement pour le/les destinataire.s en "Ce message a été rappelé";
Le backend nettoie le sujet du message, et les front devront mettre la traduction adéquate (pourrait être différente entre web et mobile) 
* Si le message a été envoyé à plusieurs personnes, le destinataire ne doit voir plus que lui dans les destinataires et pas les autres;
* Supprimer les pièces jointes pour les destinataires uniquement.
Par effet de bord, cela masquera les PJs côté front pour les destinataires de messages rappelés
+ petit fix sur les actions visibles dans ce cas-là (pour revue par @damienromito :pray: )
[COCO-4163](https://edifice-community.atlassian.net/browse/WB-4163)
dumb manual …
> feat(conversation): #WB-4163, hide unwanted data from RECALL messages

- conversation/frontend/src/features/menu/components/DesktopMenu.tsx
- conversation/frontend/src/features/menu/components/MobileMenu.tsx
- conversation/frontend/src/features/modals/CreateFolderModal.tsx
- conversation/frontend/src/features/modals/RenameFolderModal.tsx
- conversation/frontend/src/routes/root/index.tsx
rename forlder modal : 
- submit with enter key
- disabled when not renamed
new folder modal : 
- limit to 3 sub folder levels
- flat folder tree in dopdown
MobileMenu : 
- multiline dropdown item to avoid overflow hidden
> fix(conversation)-WB-4015 user folders modals

- conversation/frontend/src/components/MessageActionDropdown/hooks/useMessageActionDropdown.tsx
- conversation/frontend/src/features/message-edit/MessageEdit.tsx
- conversation/frontend/src/features/message-edit/components/MessageSaveDate.tsx
- conversation/frontend/src/features/message-edit/hooks/useAutoSaveMessage.tsx
- conversation/frontend/src/features/message-list/components/MessageItem.tsx
- conversation/frontend/src/routes/pages/Folder.tsx
- conversation/frontend/src/services/queries/attachment.ts
- conversation/frontend/src/services/queries/folder.test.tsx
- conversation/frontend/src/services/queries/folder.ts
- conversation/frontend/src/services/queries/hooks/useDeleteMessageFromQueryCache.ts
- conversation/frontend/src/services/queries/hooks/useUpdateFolderBadgeCountQueryCache.ts
- conversation/frontend/src/services/queries/message.ts
- update message hooks (react-query cache and invalidations)
fix draft issues :
- Le brouillon s'enregistre automatiquement une seule fois
- La liste des messages dans les brouillons ne se met pas à jour automatiquement si on clique sur sauvegardé
- Brouillon non souhaité créé
> fix(conversation): #COCO-4203 messages invalidations and query cache

- timeline/src/main/java/org/entcore/timeline/services/impl/FlashMsgServiceMongoImpl.java
- timeline/src/main/java/org/entcore/timeline/services/impl/FlashMsgServiceSqlImpl.java
change: Modify the query to retrieve flash message to differentiate V1 vs V2 and exclude domain check for V2
issue: V2 message can't be display on a different domain than the one use at its creation. This behavior is correct for t V1 messages but not for V2 messages.
[(Enter here Jira or Redmine ticket(s) links)](https://edifice-community.atlassian.net/browse/COCO-1570)
Make a flash message into v2 console
View it on another URL
As central administrator I create a flash message V1 on domain localhost. 
When I navigate with another user to timeline on localhost1d
Then don't see the message
As central administrator I create a flash message V1 on domain localhost. 
When I navigate with another user to …
> fix(timeline): #COCO-1570 disable domain filter on flash message V2

- admin/src/main/ts/package.json
- admin/src/main/ts/src/app/management/message-flash/form/message-flash-form/message-flash-form.component.ts
In Flash message management, using a timezone with an important gap lead to wrong date be persisted in database (for example, tahiti timezone). 
COCO-3538
1. As a user with rights to create / edit flash message, with UTC-10 in local at 3:00AM local, I create a message for today to tomorrow
2. I save the message
3. The message in the list should have the same boundaries
4. Editing the message should display the same boundaries
1. As a user with rights to create / edit flash message, with UTC+2 in local at 15:00 local, I create a message for today to tomorrow
2. I save the message
3. The message in the list should have the same boundaries
4. Editing the message should display the same boundaries
1. As a …
> fix-COCO-3538-timezone-flash-message

- conversation/frontend/src/features/menu/components/DesktopMenu.tsx
- conversation/frontend/src/features/message-list/MessageList.test.tsx
- conversation/frontend/src/features/message-list/MessageList.tsx
- conversation/frontend/src/routes/pages/Message.tsx
- conversation/frontend/src/services/queries/folder.ts
- conversation/frontend/src/services/queries/message.ts
- conversation/frontend/src/services/queries/utils.ts
- conversation/frontend/src/services/utils.ts
React-query optimisation
•	Éviter de recharger plusieurs pages lorsque le cache est invalidé : création du helper invalidateQueriesWithFirstPage.
•	Éviter le chargement de plusieurs pages à cause du scroll partagé entre différentes listes : remonter en haut de la liste lors du changement d’onglet.
•	Correction du hook useMessage qui modifiait le cache d’une query. Si cette query était invalidée avant la modification, celle-ci était écrasée. L’action a été déplacée hors du hook et est désormais appelée directement dans le composant.
- Performance impacts (think …
> fix(conversation): #COCO fix optimize infinite queries

- tests/src/test/js/it/scenarios/position/_aaf-import-before.ts
Les tests ITs ne fonctionne pas pour la partie import aaf => il semblerait que le temps d'attente pour l'import soit un peu juste
https://edifice-community.atlassian.net/browse/COCO-4324
Lancer les tests its => verfier qu'ils fonctionnent
> Fix coco 4324 fix it tests

- broker-parent/broker-api/src/main/java/org/entcore/broker/api/BrokerListener.java
- broker-parent/broker-api/src/main/java/org/entcore/broker/api/utils/BrokerProxyUtils.java
- broker-parent/broker-api/src/test/java/org/entcore/broker/api/utils/BrokerProxyUtilsTest.java
- broker-parent/broker-api/src/test/java/org/entcore/broker/api/utils/dummy/DummierProxy.java
- broker-parent/broker-api/src/test/java/org/entcore/broker/api/utils/dummy/DummyProxy.java
- broker-parent/broker-api/src/test/java/org/entcore/broker/api/utils/dummy/DummyProxyImpl.java
- broker-parent/broker-api/src/test/java/org/entcore/broker/api/utils/dummy/ExempleRequestDTO.java
- broker-parent/broker-api/src/test/java/org/entcore/broker/api/utils/dummy/ExempleResponseDTO.java
- docker-compose.yml
Cette PR permet au mécanisme de création des proxy NATS/EventBus de mieux détecter les annotations @BrokerListener lorsque celles-ci proviennent d'une classe héritée. Comme en Java les annotations de méthode ne sont pas héritées il faut "manuellement" aller les chercher récursivement sur la `super` classe.
RBACK-90
Ajout de nouveaux tests unitaires.
> feat: #RBACk-90, support the detection of @BrokerListener on methods inherited from super classes

- common/src/main/java/org/entcore/common/s3/S3Client.java
With ObjectStorage, if the content-type is wrong, downloads could be in error (mobile...).
If the content-type is present in mongo metadata and if metadata are passed to downloadFile, we will use it.
[#COCO-4321](https://edifice-community.atlassian.net/browse/COCO-4321)
> fix(common): #COCO-4321, fix object storage download content type

- common/src/main/java/org/entcore/common/communication/CommunicationUtils.java
- common/src/main/java/org/entcore/common/share/impl/GenericShareService.java
- communication/src/main/java/org/entcore/communication/controllers/CommunicationController.java
Exclude `CommunityMemberGroup` and `CommunityAdminGroup` from search in:
- `POST /communication/visible` API
- `GenericSearchService`, used in applications share panel to search users and groups
https://edifice-community.atlassian.net/browse/PEDAGO-3031
> fix(communication): #PEDAGO-3031, exclude CommunityMemberGroup and CommunityAdminGroup from visibles and share search

- directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserBookService.java
Fix null pointer exception due to queryPerson result being empty because the used id is not a person but a group 
https://edifice-community.atlassian.net/browse/COCO-4590
call GET /userbook/api/person?id={id}&type=undefined with the id of a group => we must have a response with a http code 4xx.
> Fix coco 4590 timeout on api person

- directory/src/main/java/org/entcore/directory/services/impl/DefaultUserBookService.java
Lorsque l'on utilise un ID de groupe au lieu d'un ID de person sur l'api /person, retourner une erreur provoque des problèmes dans zimbra. On doit retourner une reponse ok vide. Il faudra rétablir l'erreur lorsque l'on aura corrigé le problème des groupes dans les favoris dans la messagerie.
https://edifice-community.atlassian.net/browse/COCO-4596
Dans la messagerie dans les destinataires, cliquer sur un groupe provenant dans un favori => on doit arriver sur une page blache avec un appel à /api/person en 200 vide
- I have updated the reminder for the version including my …
> fix-(communication): #COCO-4596 return 200 empty when error occured 

- conversation/frontend/src/services/queries/folder.ts
When we delete a folder all the message go to the parent / trash we need to invalidate the query for this folder.
> fix(conversation): #COCO-4475 refresh folder after delete folder

- infra/src/main/java/org/entcore/infra/controllers/EventStoreController.java
- infra/src/main/java/org/entcore/infra/services/EventStoreService.java
- infra/src/main/java/org/entcore/infra/services/PartialResults.java
- infra/src/main/java/org/entcore/infra/services/impl/MongoDbEventStore.java
Ajout d'une nouvelle route retournant les événements de l'ENT avec une pagination simple afin d'éviter des requêtes en base trop coûteuse.
Lorsque la requête arrive, on va chercher n+1 (n étant configurable) événements. Si on en trouve n+1 alors on en renvoie que n mais on positionne le header X-HAS-MORE à true
> hotfix: #ENABLING-393, add a new route to paginate events fetch

- broker-parent/broker-api/src/main/java/org/entcore/broker/api/dto/session/RefreshSessionRequestDTO.java
- broker-parent/broker-api/src/main/java/org/entcore/broker/api/dto/session/RefreshSessionResponseDTO.java
- broker-parent/broker-api/src/main/java/org/entcore/broker/api/dto/session/SessionDto.java
- broker-parent/broker-proxy/src/main/java/org/entcore/broker/proxy/SessionBrokerListener.java
- session/src/main/java/org/entcore/session/AuthManager.java
- session/src/main/java/org/entcore/session/SessionBrokerListenerImpl.java
Cette évo permet de mettre à jour la session via le broker (si refreshonly est à vrai le sessionId ne change pas)
#pedago-2640
>  feat: #pedago-3032, add session refresh api to broker

- conversation/backend/src/main/java/org/entcore/conversation/service/impl/SqlConversationService.java
Une mauvaise gestion d'un handler sur une requête sql dans SQLConversationService provoque une regression sur les notifications
https://edifice-community.atlassian.net/browse/COCO-4674
> Fix coco 4674 fix wrong handle result in sql convsersation

- conversation/frontend/src/services/queries/hooks/useDeleteMessageFromQueryCache.ts
- conversation/frontend/src/services/queries/message.ts
Navigate was blocked due to an error on useDeleteMessagesFromQueryCache
And draft could be created even if a message was already saved.
> fix(conversation): #COCO-4662 navigate to inbox after sending message

- conversation/frontend/src/features/message-edit/components/RecipientListAvatar.tsx
- conversation/frontend/src/features/message-edit/components/RecipientListItem.tsx
- conversation/frontend/src/features/message-edit/components/RecipientListSelectedItem.tsx
- conversation/frontend/src/hooks/useInitMessage.tsx
- conversation/frontend/src/models/visible.ts
- conversation/frontend/src/services/api/userService.ts
Broadcast group must be added in CCI field and not in TO.  We now can get the type from the visible callback and then separate group.
> fix(conversation): #COCO-4643 add broadcast group to cci

- broker-parent/broker/src/main/java/org/entcore/broker/client/BrokerClientFactory.java
- broker-parent/broker/src/main/java/org/entcore/broker/client/NoOpBrokerClient.java
Ce commit fournit une implémentation du BrokerClient qui ne fait rien et renvoie toujours une réponse pour éviter des erreurs dans les environnement sans nats (donc sans broker)
#PEDAGO-2646
> fix: #PEDAGO-2646, config to disable broker

- communication/src/main/java/org/entcore/communication/services/impl/DefaultCommunicationService.java
- feeder/src/main/java/org/entcore/feeder/utils/Validator.java
Le système garde les appostrophes dans le displayNameSearchField contrairement au nom et prenom, ce qui perturbe la recherche => suppression lors d'une mise à jour de l'appostrophe
https://edifice-community.atlassian.net/browse/COCO-4720
> fix-(communication,feeder): #COCO-4720 display name search field keep ', delete it
